// <auto-generated/>
#pragma warning disable CS0618
using EveStableInfrastructure.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace EveStableInfrastructure.Corporation.Item.Mining.Extractions
{
    /// <summary>
    /// Builds and executes requests for operations under \corporation\{corporation_id}\mining\extractions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExtractionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Corporation.Item.Mining.Extractions.ExtractionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExtractionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/corporation/{corporation_id}/mining/extractions{?page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Corporation.Item.Mining.Extractions.ExtractionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExtractionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/corporation/{corporation_id}/mining/extractions{?page*}", rawUrl)
        {
        }
        /// <summary>
        /// Extraction timers for all moon chunks being extracted by refineries belonging to a corporation.
        /// </summary>
        /// <returns>A List&lt;global::EveStableInfrastructure.Models.CorporationCorporationIdMiningExtractionsGet&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::EveStableInfrastructure.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::EveStableInfrastructure.Models.CorporationCorporationIdMiningExtractionsGet>?> GetAsync(Action<RequestConfiguration<global::EveStableInfrastructure.Corporation.Item.Mining.Extractions.ExtractionsRequestBuilder.ExtractionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::EveStableInfrastructure.Models.CorporationCorporationIdMiningExtractionsGet>> GetAsync(Action<RequestConfiguration<global::EveStableInfrastructure.Corporation.Item.Mining.Extractions.ExtractionsRequestBuilder.ExtractionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::EveStableInfrastructure.Models.Error.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::EveStableInfrastructure.Models.CorporationCorporationIdMiningExtractionsGet>(requestInfo, global::EveStableInfrastructure.Models.CorporationCorporationIdMiningExtractionsGet.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Extraction timers for all moon chunks being extracted by refineries belonging to a corporation.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::EveStableInfrastructure.Corporation.Item.Mining.Extractions.ExtractionsRequestBuilder.ExtractionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::EveStableInfrastructure.Corporation.Item.Mining.Extractions.ExtractionsRequestBuilder.ExtractionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Corporation.Item.Mining.Extractions.ExtractionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::EveStableInfrastructure.Corporation.Item.Mining.Extractions.ExtractionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::EveStableInfrastructure.Corporation.Item.Mining.Extractions.ExtractionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Extraction timers for all moon chunks being extracted by refineries belonging to a corporation.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExtractionsRequestBuilderGetQueryParameters 
        {
            [QueryParameter("page")]
            public int? Page { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExtractionsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::EveStableInfrastructure.Corporation.Item.Mining.Extractions.ExtractionsRequestBuilder.ExtractionsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
