// <auto-generated/>
#pragma warning disable CS0618
using EveStableInfrastructure.Corporation.Item.Mining;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EveStableInfrastructure.Corporation.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \corporation\{corporation_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithCorporation_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The mining property</summary>
        public global::EveStableInfrastructure.Corporation.Item.Mining.MiningRequestBuilder Mining
        {
            get => new global::EveStableInfrastructure.Corporation.Item.Mining.MiningRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Corporation.Item.WithCorporation_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCorporation_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/corporation/{corporation_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Corporation.Item.WithCorporation_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCorporation_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/corporation/{corporation_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
