// <auto-generated/>
#pragma warning disable CS0618
using EveStableInfrastructure.Corporations.Item.Projects.Item;
using EveStableInfrastructure.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace EveStableInfrastructure.Corporations.Item.Projects
{
    /// <summary>
    /// Builds and executes requests for operations under \corporations\{corporation_id}\projects
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the EveStableInfrastructure.corporations.item.projects.item collection</summary>
        /// <param name="position">The ID of the project</param>
        /// <returns>A <see cref="global::EveStableInfrastructure.Corporations.Item.Projects.Item.WithProject_ItemRequestBuilder"/></returns>
        public global::EveStableInfrastructure.Corporations.Item.Projects.Item.WithProject_ItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("project_id", position);
                return new global::EveStableInfrastructure.Corporations.Item.Projects.Item.WithProject_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the EveStableInfrastructure.corporations.item.projects.item collection</summary>
        /// <param name="position">The ID of the project</param>
        /// <returns>A <see cref="global::EveStableInfrastructure.Corporations.Item.Projects.Item.WithProject_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::EveStableInfrastructure.Corporations.Item.Projects.Item.WithProject_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("project_id", position);
                return new global::EveStableInfrastructure.Corporations.Item.Projects.Item.WithProject_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Corporations.Item.Projects.ProjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/corporations/{corporation_id}/projects{?after,before,limit,state}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Corporations.Item.Projects.ProjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/corporations/{corporation_id}/projects{?after,before,limit,state}", rawUrl)
        {
        }
        /// <summary>
        /// Listing of all (active) corporation projects.
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsListing"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::EveStableInfrastructure.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::EveStableInfrastructure.Models.CorporationsProjectsListing?> GetAsync(Action<RequestConfiguration<global::EveStableInfrastructure.Corporations.Item.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::EveStableInfrastructure.Models.CorporationsProjectsListing> GetAsync(Action<RequestConfiguration<global::EveStableInfrastructure.Corporations.Item.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::EveStableInfrastructure.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::EveStableInfrastructure.Models.CorporationsProjectsListing>(requestInfo, global::EveStableInfrastructure.Models.CorporationsProjectsListing.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Listing of all (active) corporation projects.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::EveStableInfrastructure.Corporations.Item.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::EveStableInfrastructure.Corporations.Item.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Corporations.Item.Projects.ProjectsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::EveStableInfrastructure.Corporations.Item.Projects.ProjectsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::EveStableInfrastructure.Corporations.Item.Projects.ProjectsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Listing of all (active) corporation projects.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProjectsRequestBuilderGetQueryParameters 
        {
            /// <summary>Return records from after this cursor (mutual exclusive with &apos;before&apos;). &apos;0&apos; to start from the beginning.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("after")]
            public string? After { get; set; }
#nullable restore
#else
            [QueryParameter("after")]
            public string After { get; set; }
#endif
            /// <summary>Return records from before this cursor (mutual exclusive with &apos;after&apos;). &apos;0&apos; to start from the end.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("before")]
            public string? Before { get; set; }
#nullable restore
#else
            [QueryParameter("before")]
            public string Before { get; set; }
#endif
            /// <summary>The amount of records to retrieve per request.</summary>
            [QueryParameter("limit")]
            public long? Limit { get; set; }
            /// <summary>Filter by state</summary>
            [Obsolete("This property is deprecated, use StateAsGetStateQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("state")]
            public string? State { get; set; }
#nullable restore
#else
            [QueryParameter("state")]
            public string State { get; set; }
#endif
            /// <summary>Filter by state</summary>
            [QueryParameter("state")]
            public global::EveStableInfrastructure.Corporations.Item.Projects.GetStateQueryParameterType? StateAsGetStateQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProjectsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::EveStableInfrastructure.Corporations.Item.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
