// <auto-generated/>
#pragma warning disable CS0618
using EveStableInfrastructure.Fleets.Item.Squads.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EveStableInfrastructure.Fleets.Item.Squads
{
    /// <summary>
    /// Builds and executes requests for operations under \fleets\{fleet_id}\squads
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SquadsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the EveStableInfrastructure.fleets.item.squads.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::EveStableInfrastructure.Fleets.Item.Squads.Item.WithSquad_ItemRequestBuilder"/></returns>
        public global::EveStableInfrastructure.Fleets.Item.Squads.Item.WithSquad_ItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("squad_id", position);
                return new global::EveStableInfrastructure.Fleets.Item.Squads.Item.WithSquad_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the EveStableInfrastructure.fleets.item.squads.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::EveStableInfrastructure.Fleets.Item.Squads.Item.WithSquad_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::EveStableInfrastructure.Fleets.Item.Squads.Item.WithSquad_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("squad_id", position);
                return new global::EveStableInfrastructure.Fleets.Item.Squads.Item.WithSquad_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Fleets.Item.Squads.SquadsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SquadsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fleets/{fleet_id}/squads", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Fleets.Item.Squads.SquadsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SquadsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fleets/{fleet_id}/squads", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
