// <auto-generated/>
#pragma warning disable CS0618
using EveStableInfrastructure.Corporation.Item.Mining.Observers.Item;
using EveStableInfrastructure.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace EveStableInfrastructure.Corporation.Item.Mining.Observers
{
    /// <summary>
    /// Builds and executes requests for operations under \corporation\{corporation_id}\mining\observers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ObserversRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the EveStableInfrastructure.corporation.item.mining.observers.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::EveStableInfrastructure.Corporation.Item.Mining.Observers.Item.WithObserver_ItemRequestBuilder"/></returns>
        public global::EveStableInfrastructure.Corporation.Item.Mining.Observers.Item.WithObserver_ItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("observer_id", position);
                return new global::EveStableInfrastructure.Corporation.Item.Mining.Observers.Item.WithObserver_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the EveStableInfrastructure.corporation.item.mining.observers.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::EveStableInfrastructure.Corporation.Item.Mining.Observers.Item.WithObserver_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::EveStableInfrastructure.Corporation.Item.Mining.Observers.Item.WithObserver_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("observer_id", position);
                return new global::EveStableInfrastructure.Corporation.Item.Mining.Observers.Item.WithObserver_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Corporation.Item.Mining.Observers.ObserversRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ObserversRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/corporation/{corporation_id}/mining/observers{?page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Corporation.Item.Mining.Observers.ObserversRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ObserversRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/corporation/{corporation_id}/mining/observers{?page*}", rawUrl)
        {
        }
        /// <summary>
        /// Paginated list of all entities capable of observing and recording mining for a corporation
        /// </summary>
        /// <returns>A List&lt;global::EveStableInfrastructure.Models.CorporationCorporationIdMiningObserversGet&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::EveStableInfrastructure.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::EveStableInfrastructure.Models.CorporationCorporationIdMiningObserversGet>?> GetAsync(Action<RequestConfiguration<global::EveStableInfrastructure.Corporation.Item.Mining.Observers.ObserversRequestBuilder.ObserversRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::EveStableInfrastructure.Models.CorporationCorporationIdMiningObserversGet>> GetAsync(Action<RequestConfiguration<global::EveStableInfrastructure.Corporation.Item.Mining.Observers.ObserversRequestBuilder.ObserversRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::EveStableInfrastructure.Models.Error.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::EveStableInfrastructure.Models.CorporationCorporationIdMiningObserversGet>(requestInfo, global::EveStableInfrastructure.Models.CorporationCorporationIdMiningObserversGet.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Paginated list of all entities capable of observing and recording mining for a corporation
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::EveStableInfrastructure.Corporation.Item.Mining.Observers.ObserversRequestBuilder.ObserversRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::EveStableInfrastructure.Corporation.Item.Mining.Observers.ObserversRequestBuilder.ObserversRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Corporation.Item.Mining.Observers.ObserversRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::EveStableInfrastructure.Corporation.Item.Mining.Observers.ObserversRequestBuilder WithUrl(string rawUrl)
        {
            return new global::EveStableInfrastructure.Corporation.Item.Mining.Observers.ObserversRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Paginated list of all entities capable of observing and recording mining for a corporation
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ObserversRequestBuilderGetQueryParameters 
        {
            [QueryParameter("page")]
            public int? Page { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ObserversRequestBuilderGetRequestConfiguration : RequestConfiguration<global::EveStableInfrastructure.Corporation.Item.Mining.Observers.ObserversRequestBuilder.ObserversRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
