// <auto-generated/>
#pragma warning disable CS0618
using EveStableInfrastructure.Universe.Stations.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EveStableInfrastructure.Universe.Stations
{
    /// <summary>
    /// Builds and executes requests for operations under \universe\stations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the EveStableInfrastructure.universe.stations.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::EveStableInfrastructure.Universe.Stations.Item.WithStation_ItemRequestBuilder"/></returns>
        public global::EveStableInfrastructure.Universe.Stations.Item.WithStation_ItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("station_id", position);
                return new global::EveStableInfrastructure.Universe.Stations.Item.WithStation_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the EveStableInfrastructure.universe.stations.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::EveStableInfrastructure.Universe.Stations.Item.WithStation_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::EveStableInfrastructure.Universe.Stations.Item.WithStation_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("station_id", position);
                return new global::EveStableInfrastructure.Universe.Stations.Item.WithStation_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Universe.Stations.StationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/universe/stations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Universe.Stations.StationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/universe/stations", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
