// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AllianceDetail : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Alliance&apos;s creator corporation ID</summary>
        public long? CreatorCorporationId { get; set; }
        /// <summary>Alliance&apos;s creator ID</summary>
        public long? CreatorId { get; set; }
        /// <summary>Alliance&apos;s founding date</summary>
        public DateTimeOffset? DateFounded { get; set; }
        /// <summary>Alliance&apos;s executor corporation ID</summary>
        public long? ExecutorCorporationId { get; set; }
        /// <summary>Alliance&apos;s faction ID</summary>
        public long? FactionId { get; set; }
        /// <summary>Alliance&apos;s name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Alliance&apos;s ticker</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ticker { get; set; }
#nullable restore
#else
        public string Ticker { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.AllianceDetail"/> and sets the default values.
        /// </summary>
        public AllianceDetail()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.AllianceDetail"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.AllianceDetail CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.AllianceDetail();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "creator_corporation_id", n => { CreatorCorporationId = n.GetLongValue(); } },
                { "creator_id", n => { CreatorId = n.GetLongValue(); } },
                { "date_founded", n => { DateFounded = n.GetDateTimeOffsetValue(); } },
                { "executor_corporation_id", n => { ExecutorCorporationId = n.GetLongValue(); } },
                { "faction_id", n => { FactionId = n.GetLongValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "ticker", n => { Ticker = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("creator_corporation_id", CreatorCorporationId);
            writer.WriteLongValue("creator_id", CreatorId);
            writer.WriteDateTimeOffsetValue("date_founded", DateFounded);
            writer.WriteLongValue("executor_corporation_id", ExecutorCorporationId);
            writer.WriteLongValue("faction_id", FactionId);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("ticker", Ticker);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
