// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CharactersCharacterIdMailGet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>From whom the mail was sent</summary>
        public long? From { get; set; }
        /// <summary>The is_read property</summary>
        public bool? IsRead { get; set; }
        /// <summary>The labels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<long?>? Labels { get; set; }
#nullable restore
#else
        public List<long?> Labels { get; set; }
#endif
        /// <summary>The mail_id property</summary>
        public long? MailId { get; set; }
        /// <summary>Recipients of the mail</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CharactersCharacterIdMailGet_recipients>? Recipients { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CharactersCharacterIdMailGet_recipients> Recipients { get; set; }
#endif
        /// <summary>Mail subject</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>When the mail was sent</summary>
        public DateTimeOffset? Timestamp { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.CharactersCharacterIdMailGet"/> and sets the default values.
        /// </summary>
        public CharactersCharacterIdMailGet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CharactersCharacterIdMailGet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.CharactersCharacterIdMailGet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.CharactersCharacterIdMailGet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "from", n => { From = n.GetLongValue(); } },
                { "is_read", n => { IsRead = n.GetBoolValue(); } },
                { "labels", n => { Labels = n.GetCollectionOfPrimitiveValues<long?>()?.AsList(); } },
                { "mail_id", n => { MailId = n.GetLongValue(); } },
                { "recipients", n => { Recipients = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.CharactersCharacterIdMailGet_recipients>(global::EveStableInfrastructure.Models.CharactersCharacterIdMailGet_recipients.CreateFromDiscriminatorValue)?.AsList(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "timestamp", n => { Timestamp = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("from", From);
            writer.WriteBoolValue("is_read", IsRead);
            writer.WriteCollectionOfPrimitiveValues<long?>("labels", Labels);
            writer.WriteLongValue("mail_id", MailId);
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.CharactersCharacterIdMailGet_recipients>("recipients", Recipients);
            writer.WriteStringValue("subject", Subject);
            writer.WriteDateTimeOffsetValue("timestamp", Timestamp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
