// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CharactersCharacterIdContractsContractIdItemsGet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>true if the contract issuer has submitted this item with the contract, false if the isser is asking for this item in the contract</summary>
        public bool? IsIncluded { get; set; }
        /// <summary>The is_singleton property</summary>
        public bool? IsSingleton { get; set; }
        /// <summary>Number of items in the stack</summary>
        public long? Quantity { get; set; }
        /// <summary>-1 indicates that the item is a singleton (non-stackable). If the item happens to be a Blueprint, -1 is an Original and -2 is a Blueprint Copy</summary>
        public long? RawQuantity { get; set; }
        /// <summary>Unique ID for the item</summary>
        public long? RecordId { get; set; }
        /// <summary>Type ID for item</summary>
        public long? TypeId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.CharactersCharacterIdContractsContractIdItemsGet"/> and sets the default values.
        /// </summary>
        public CharactersCharacterIdContractsContractIdItemsGet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CharactersCharacterIdContractsContractIdItemsGet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.CharactersCharacterIdContractsContractIdItemsGet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.CharactersCharacterIdContractsContractIdItemsGet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "is_included", n => { IsIncluded = n.GetBoolValue(); } },
                { "is_singleton", n => { IsSingleton = n.GetBoolValue(); } },
                { "quantity", n => { Quantity = n.GetLongValue(); } },
                { "raw_quantity", n => { RawQuantity = n.GetLongValue(); } },
                { "record_id", n => { RecordId = n.GetLongValue(); } },
                { "type_id", n => { TypeId = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("is_included", IsIncluded);
            writer.WriteBoolValue("is_singleton", IsSingleton);
            writer.WriteLongValue("quantity", Quantity);
            writer.WriteLongValue("raw_quantity", RawQuantity);
            writer.WriteLongValue("record_id", RecordId);
            writer.WriteLongValue("type_id", TypeId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
