// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CharactersCharacterIdAssetsGet_location_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "station")]
        #pragma warning disable CS1591
        Station,
        #pragma warning restore CS1591
        [EnumMember(Value = "solar_system")]
        #pragma warning disable CS1591
        Solar_system,
        #pragma warning restore CS1591
        [EnumMember(Value = "item")]
        #pragma warning disable CS1591
        Item,
        #pragma warning restore CS1591
        [EnumMember(Value = "other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
