// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace EveStableInfrastructure.Models
{
    /// <summary>Member’s role in fleet</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CharactersCharacterIdFleetGet_role
    {
        [EnumMember(Value = "fleet_commander")]
        #pragma warning disable CS1591
        Fleet_commander,
        #pragma warning restore CS1591
        [EnumMember(Value = "squad_commander")]
        #pragma warning disable CS1591
        Squad_commander,
        #pragma warning restore CS1591
        [EnumMember(Value = "squad_member")]
        #pragma warning disable CS1591
        Squad_member,
        #pragma warning restore CS1591
        [EnumMember(Value = "wing_commander")]
        #pragma warning disable CS1591
        Wing_commander,
        #pragma warning restore CS1591
    }
}
