// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CharactersCharacterIdIndustryJobsGet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Job activity ID</summary>
        public long? ActivityId { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The blueprint_id property</summary>
        public long? BlueprintId { get; set; }
        /// <summary>Location ID of the location from which the blueprint was installed. Normally a station ID, but can also be an asset (e.g. container) or corporation facility</summary>
        public long? BlueprintLocationId { get; set; }
        /// <summary>The blueprint_type_id property</summary>
        public long? BlueprintTypeId { get; set; }
        /// <summary>ID of the character which completed this job</summary>
        public long? CompletedCharacterId { get; set; }
        /// <summary>Date and time when this job was completed</summary>
        public DateTimeOffset? CompletedDate { get; set; }
        /// <summary>The sume of job installation fee and industry facility tax</summary>
        public double? Cost { get; set; }
        /// <summary>Job duration in seconds</summary>
        public long? Duration { get; set; }
        /// <summary>Date and time when this job finished</summary>
        public DateTimeOffset? EndDate { get; set; }
        /// <summary>ID of the facility where this job is running</summary>
        public long? FacilityId { get; set; }
        /// <summary>ID of the character which installed this job</summary>
        public long? InstallerId { get; set; }
        /// <summary>Unique job ID</summary>
        public long? JobId { get; set; }
        /// <summary>Number of runs blueprint is licensed for</summary>
        public long? LicensedRuns { get; set; }
        /// <summary>Location ID of the location to which the output of the job will be delivered. Normally a station ID, but can also be a corporation facility</summary>
        public long? OutputLocationId { get; set; }
        /// <summary>Date and time when this job was paused (i.e. time when the facility where this job was installed went offline)</summary>
        public DateTimeOffset? PauseDate { get; set; }
        /// <summary>Chance of success for invention</summary>
        public double? Probability { get; set; }
        /// <summary>Type ID of product (manufactured, copied or invented)</summary>
        public long? ProductTypeId { get; set; }
        /// <summary>Number of runs for a manufacturing job, or number of copies to make for a blueprint copy</summary>
        public long? Runs { get; set; }
        /// <summary>Date and time when this job started</summary>
        public DateTimeOffset? StartDate { get; set; }
        /// <summary>ID of the station where industry facility is located</summary>
        public long? StationId { get; set; }
        /// <summary>The status property</summary>
        public global::EveStableInfrastructure.Models.CharactersCharacterIdIndustryJobsGet_status? Status { get; set; }
        /// <summary>Number of successful runs for this job. Equal to runs unless this is an invention job</summary>
        public long? SuccessfulRuns { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.CharactersCharacterIdIndustryJobsGet"/> and sets the default values.
        /// </summary>
        public CharactersCharacterIdIndustryJobsGet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CharactersCharacterIdIndustryJobsGet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.CharactersCharacterIdIndustryJobsGet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.CharactersCharacterIdIndustryJobsGet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activity_id", n => { ActivityId = n.GetLongValue(); } },
                { "blueprint_id", n => { BlueprintId = n.GetLongValue(); } },
                { "blueprint_location_id", n => { BlueprintLocationId = n.GetLongValue(); } },
                { "blueprint_type_id", n => { BlueprintTypeId = n.GetLongValue(); } },
                { "completed_character_id", n => { CompletedCharacterId = n.GetLongValue(); } },
                { "completed_date", n => { CompletedDate = n.GetDateTimeOffsetValue(); } },
                { "cost", n => { Cost = n.GetDoubleValue(); } },
                { "duration", n => { Duration = n.GetLongValue(); } },
                { "end_date", n => { EndDate = n.GetDateTimeOffsetValue(); } },
                { "facility_id", n => { FacilityId = n.GetLongValue(); } },
                { "installer_id", n => { InstallerId = n.GetLongValue(); } },
                { "job_id", n => { JobId = n.GetLongValue(); } },
                { "licensed_runs", n => { LicensedRuns = n.GetLongValue(); } },
                { "output_location_id", n => { OutputLocationId = n.GetLongValue(); } },
                { "pause_date", n => { PauseDate = n.GetDateTimeOffsetValue(); } },
                { "probability", n => { Probability = n.GetDoubleValue(); } },
                { "product_type_id", n => { ProductTypeId = n.GetLongValue(); } },
                { "runs", n => { Runs = n.GetLongValue(); } },
                { "start_date", n => { StartDate = n.GetDateTimeOffsetValue(); } },
                { "station_id", n => { StationId = n.GetLongValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::EveStableInfrastructure.Models.CharactersCharacterIdIndustryJobsGet_status>(); } },
                { "successful_runs", n => { SuccessfulRuns = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("activity_id", ActivityId);
            writer.WriteLongValue("blueprint_id", BlueprintId);
            writer.WriteLongValue("blueprint_location_id", BlueprintLocationId);
            writer.WriteLongValue("blueprint_type_id", BlueprintTypeId);
            writer.WriteLongValue("completed_character_id", CompletedCharacterId);
            writer.WriteDateTimeOffsetValue("completed_date", CompletedDate);
            writer.WriteDoubleValue("cost", Cost);
            writer.WriteLongValue("duration", Duration);
            writer.WriteDateTimeOffsetValue("end_date", EndDate);
            writer.WriteLongValue("facility_id", FacilityId);
            writer.WriteLongValue("installer_id", InstallerId);
            writer.WriteLongValue("job_id", JobId);
            writer.WriteLongValue("licensed_runs", LicensedRuns);
            writer.WriteLongValue("output_location_id", OutputLocationId);
            writer.WriteDateTimeOffsetValue("pause_date", PauseDate);
            writer.WriteDoubleValue("probability", Probability);
            writer.WriteLongValue("product_type_id", ProductTypeId);
            writer.WriteLongValue("runs", Runs);
            writer.WriteDateTimeOffsetValue("start_date", StartDate);
            writer.WriteLongValue("station_id", StationId);
            writer.WriteEnumValue<global::EveStableInfrastructure.Models.CharactersCharacterIdIndustryJobsGet_status>("status", Status);
            writer.WriteLongValue("successful_runs", SuccessfulRuns);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
