// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace EveStableInfrastructure.Models
{
    /// <summary>To whom the contract is available</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CorporationsCorporationIdContractsGet_availability
    {
        [EnumMember(Value = "public")]
        #pragma warning disable CS1591
        Public,
        #pragma warning restore CS1591
        [EnumMember(Value = "personal")]
        #pragma warning disable CS1591
        Personal,
        #pragma warning restore CS1591
        [EnumMember(Value = "corporation")]
        #pragma warning disable CS1591
        Corporation,
        #pragma warning restore CS1591
        [EnumMember(Value = "alliance")]
        #pragma warning disable CS1591
        Alliance,
        #pragma warning restore CS1591
    }
}
