// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    /// <summary>
    /// Lost ship
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CorporationsProjectsDetailConfigurationlostship : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Identity of killer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_identities>? Identities { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_identities> Identities { get; set; }
#endif
        /// <summary>Location of lost ship</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_locations>? Locations { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_locations> Locations { get; set; }
#endif
        /// <summary>Ship-type of lost ship</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_ships>? Ships { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_ships> Ships { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship"/> and sets the default values.
        /// </summary>
        public CorporationsProjectsDetailConfigurationlostship()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "identities", n => { Identities = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_identities>(global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_identities.CreateFromDiscriminatorValue)?.AsList(); } },
                { "locations", n => { Locations = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_locations>(global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_locations.CreateFromDiscriminatorValue)?.AsList(); } },
                { "ships", n => { Ships = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_ships>(global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_ships.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_identities>("identities", Identities);
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_locations>("locations", Locations);
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_ships>("ships", Ships);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember1"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember2"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember3"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember4"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CorporationsProjectsDetailConfigurationlostship_identities : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember1? CorporationsProjectsDetailConfigurationlostshipIdentitiesMember1 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember1 CorporationsProjectsDetailConfigurationlostshipIdentitiesMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember2? CorporationsProjectsDetailConfigurationlostshipIdentitiesMember2 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember2 CorporationsProjectsDetailConfigurationlostshipIdentitiesMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember3? CorporationsProjectsDetailConfigurationlostshipIdentitiesMember3 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember3 CorporationsProjectsDetailConfigurationlostshipIdentitiesMember3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember4? CorporationsProjectsDetailConfigurationlostshipIdentitiesMember4 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember4 CorporationsProjectsDetailConfigurationlostshipIdentitiesMember4 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_identities"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_identities CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_identities();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationlostshipIdentitiesMember1 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationlostshipIdentitiesMember2 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationlostshipIdentitiesMember3 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember3();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationlostshipIdentitiesMember4 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember4();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CorporationsProjectsDetailConfigurationlostshipIdentitiesMember1 != null)
                {
                    return CorporationsProjectsDetailConfigurationlostshipIdentitiesMember1.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationlostshipIdentitiesMember2 != null)
                {
                    return CorporationsProjectsDetailConfigurationlostshipIdentitiesMember2.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationlostshipIdentitiesMember3 != null)
                {
                    return CorporationsProjectsDetailConfigurationlostshipIdentitiesMember3.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationlostshipIdentitiesMember4 != null)
                {
                    return CorporationsProjectsDetailConfigurationlostshipIdentitiesMember4.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CorporationsProjectsDetailConfigurationlostshipIdentitiesMember1 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember1>(null, CorporationsProjectsDetailConfigurationlostshipIdentitiesMember1);
                }
                else if(CorporationsProjectsDetailConfigurationlostshipIdentitiesMember2 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember2>(null, CorporationsProjectsDetailConfigurationlostshipIdentitiesMember2);
                }
                else if(CorporationsProjectsDetailConfigurationlostshipIdentitiesMember3 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember3>(null, CorporationsProjectsDetailConfigurationlostshipIdentitiesMember3);
                }
                else if(CorporationsProjectsDetailConfigurationlostshipIdentitiesMember4 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_identitiesMember4>(null, CorporationsProjectsDetailConfigurationlostshipIdentitiesMember4);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember1"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember2"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember3"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CorporationsProjectsDetailConfigurationlostship_locations : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember1? CorporationsProjectsDetailConfigurationlostshipLocationsMember1 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember1 CorporationsProjectsDetailConfigurationlostshipLocationsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember2? CorporationsProjectsDetailConfigurationlostshipLocationsMember2 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember2 CorporationsProjectsDetailConfigurationlostshipLocationsMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember3? CorporationsProjectsDetailConfigurationlostshipLocationsMember3 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember3 CorporationsProjectsDetailConfigurationlostshipLocationsMember3 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_locations"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_locations CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_locations();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationlostshipLocationsMember1 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationlostshipLocationsMember2 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationlostshipLocationsMember3 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember3();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CorporationsProjectsDetailConfigurationlostshipLocationsMember1 != null)
                {
                    return CorporationsProjectsDetailConfigurationlostshipLocationsMember1.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationlostshipLocationsMember2 != null)
                {
                    return CorporationsProjectsDetailConfigurationlostshipLocationsMember2.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationlostshipLocationsMember3 != null)
                {
                    return CorporationsProjectsDetailConfigurationlostshipLocationsMember3.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CorporationsProjectsDetailConfigurationlostshipLocationsMember1 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember1>(null, CorporationsProjectsDetailConfigurationlostshipLocationsMember1);
                }
                else if(CorporationsProjectsDetailConfigurationlostshipLocationsMember2 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember2>(null, CorporationsProjectsDetailConfigurationlostshipLocationsMember2);
                }
                else if(CorporationsProjectsDetailConfigurationlostshipLocationsMember3 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_locationsMember3>(null, CorporationsProjectsDetailConfigurationlostshipLocationsMember3);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_shipsMember1"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_shipsMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CorporationsProjectsDetailConfigurationlostship_ships : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_shipsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_shipsMember1? CorporationsProjectsDetailConfigurationlostshipShipsMember1 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_shipsMember1 CorporationsProjectsDetailConfigurationlostshipShipsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_shipsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_shipsMember2? CorporationsProjectsDetailConfigurationlostshipShipsMember2 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_shipsMember2 CorporationsProjectsDetailConfigurationlostshipShipsMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_ships"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_ships CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship.CorporationsProjectsDetailConfigurationlostship_ships();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationlostshipShipsMember1 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_shipsMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationlostshipShipsMember2 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_shipsMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CorporationsProjectsDetailConfigurationlostshipShipsMember1 != null)
                {
                    return CorporationsProjectsDetailConfigurationlostshipShipsMember1.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationlostshipShipsMember2 != null)
                {
                    return CorporationsProjectsDetailConfigurationlostshipShipsMember2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CorporationsProjectsDetailConfigurationlostshipShipsMember1 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_shipsMember1>(null, CorporationsProjectsDetailConfigurationlostshipShipsMember1);
                }
                else if(CorporationsProjectsDetailConfigurationlostshipShipsMember2 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationlostship_shipsMember2>(null, CorporationsProjectsDetailConfigurationlostshipShipsMember2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
