// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    /// <summary>
    /// Ship insurance
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CorporationsProjectsDetailConfigurationshipinsurance : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Conflict type</summary>
        public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_conflict_type? ConflictType { get; set; }
        /// <summary>Identity of killer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_identities>? Identities { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_identities> Identities { get; set; }
#endif
        /// <summary>Location of lost ship</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_locations>? Locations { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_locations> Locations { get; set; }
#endif
        /// <summary>Reimburse implants</summary>
        public bool? ReimburseImplants { get; set; }
        /// <summary>Ship-type of lost ship</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_ships>? Ships { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_ships> Ships { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance"/> and sets the default values.
        /// </summary>
        public CorporationsProjectsDetailConfigurationshipinsurance()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "conflict_type", n => { ConflictType = n.GetEnumValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_conflict_type>(); } },
                { "identities", n => { Identities = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_identities>(global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_identities.CreateFromDiscriminatorValue)?.AsList(); } },
                { "locations", n => { Locations = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_locations>(global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_locations.CreateFromDiscriminatorValue)?.AsList(); } },
                { "reimburse_implants", n => { ReimburseImplants = n.GetBoolValue(); } },
                { "ships", n => { Ships = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_ships>(global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_ships.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_conflict_type>("conflict_type", ConflictType);
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_identities>("identities", Identities);
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_locations>("locations", Locations);
            writer.WriteBoolValue("reimburse_implants", ReimburseImplants);
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_ships>("ships", Ships);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember1"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember2"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember3"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember4"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CorporationsProjectsDetailConfigurationshipinsurance_identities : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember1? CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember1 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember1 CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember2? CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember2 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember2 CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember3? CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember3 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember3 CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember4? CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember4 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember4 CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember4 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_identities"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_identities CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_identities();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember1 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember2 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember3 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember3();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember4 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember4();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember1 != null)
                {
                    return CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember1.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember2 != null)
                {
                    return CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember2.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember3 != null)
                {
                    return CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember3.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember4 != null)
                {
                    return CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember4.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember1 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember1>(null, CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember1);
                }
                else if(CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember2 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember2>(null, CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember2);
                }
                else if(CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember3 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember3>(null, CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember3);
                }
                else if(CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember4 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_identitiesMember4>(null, CorporationsProjectsDetailConfigurationshipinsuranceIdentitiesMember4);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember1"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember2"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember3"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CorporationsProjectsDetailConfigurationshipinsurance_locations : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember1? CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember1 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember1 CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember2? CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember2 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember2 CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember3? CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember3 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember3 CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember3 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_locations"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_locations CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_locations();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember1 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember2 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember3 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember3();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember1 != null)
                {
                    return CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember1.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember2 != null)
                {
                    return CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember2.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember3 != null)
                {
                    return CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember3.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember1 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember1>(null, CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember1);
                }
                else if(CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember2 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember2>(null, CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember2);
                }
                else if(CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember3 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_locationsMember3>(null, CorporationsProjectsDetailConfigurationshipinsuranceLocationsMember3);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_shipsMember1"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_shipsMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CorporationsProjectsDetailConfigurationshipinsurance_ships : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_shipsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_shipsMember1? CorporationsProjectsDetailConfigurationshipinsuranceShipsMember1 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_shipsMember1 CorporationsProjectsDetailConfigurationshipinsuranceShipsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_shipsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_shipsMember2? CorporationsProjectsDetailConfigurationshipinsuranceShipsMember2 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_shipsMember2 CorporationsProjectsDetailConfigurationshipinsuranceShipsMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_ships"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_ships CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance.CorporationsProjectsDetailConfigurationshipinsurance_ships();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationshipinsuranceShipsMember1 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_shipsMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationshipinsuranceShipsMember2 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_shipsMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CorporationsProjectsDetailConfigurationshipinsuranceShipsMember1 != null)
                {
                    return CorporationsProjectsDetailConfigurationshipinsuranceShipsMember1.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationshipinsuranceShipsMember2 != null)
                {
                    return CorporationsProjectsDetailConfigurationshipinsuranceShipsMember2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CorporationsProjectsDetailConfigurationshipinsuranceShipsMember1 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_shipsMember1>(null, CorporationsProjectsDetailConfigurationshipinsuranceShipsMember1);
                }
                else if(CorporationsProjectsDetailConfigurationshipinsuranceShipsMember2 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationshipinsurance_shipsMember2>(null, CorporationsProjectsDetailConfigurationshipinsuranceShipsMember2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
