// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CorporationsCorporationIdTitlesGet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The grantable_roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_grantable_roles?>? GrantableRoles { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_grantable_roles?> GrantableRoles { get; set; }
#endif
        /// <summary>The grantable_roles_at_base property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_grantable_roles_at_base?>? GrantableRolesAtBase { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_grantable_roles_at_base?> GrantableRolesAtBase { get; set; }
#endif
        /// <summary>The grantable_roles_at_hq property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_grantable_roles_at_hq?>? GrantableRolesAtHq { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_grantable_roles_at_hq?> GrantableRolesAtHq { get; set; }
#endif
        /// <summary>The grantable_roles_at_other property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_grantable_roles_at_other?>? GrantableRolesAtOther { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_grantable_roles_at_other?> GrantableRolesAtOther { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_roles?>? Roles { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_roles?> Roles { get; set; }
#endif
        /// <summary>The roles_at_base property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_roles_at_base?>? RolesAtBase { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_roles_at_base?> RolesAtBase { get; set; }
#endif
        /// <summary>The roles_at_hq property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_roles_at_hq?>? RolesAtHq { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_roles_at_hq?> RolesAtHq { get; set; }
#endif
        /// <summary>The roles_at_other property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_roles_at_other?>? RolesAtOther { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_roles_at_other?> RolesAtOther { get; set; }
#endif
        /// <summary>The title_id property</summary>
        public long? TitleId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet"/> and sets the default values.
        /// </summary>
        public CorporationsCorporationIdTitlesGet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "grantable_roles", n => { GrantableRoles = n.GetCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_grantable_roles>()?.AsList(); } },
                { "grantable_roles_at_base", n => { GrantableRolesAtBase = n.GetCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_grantable_roles_at_base>()?.AsList(); } },
                { "grantable_roles_at_hq", n => { GrantableRolesAtHq = n.GetCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_grantable_roles_at_hq>()?.AsList(); } },
                { "grantable_roles_at_other", n => { GrantableRolesAtOther = n.GetCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_grantable_roles_at_other>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "roles", n => { Roles = n.GetCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_roles>()?.AsList(); } },
                { "roles_at_base", n => { RolesAtBase = n.GetCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_roles_at_base>()?.AsList(); } },
                { "roles_at_hq", n => { RolesAtHq = n.GetCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_roles_at_hq>()?.AsList(); } },
                { "roles_at_other", n => { RolesAtOther = n.GetCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_roles_at_other>()?.AsList(); } },
                { "title_id", n => { TitleId = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_grantable_roles>("grantable_roles", GrantableRoles);
            writer.WriteCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_grantable_roles_at_base>("grantable_roles_at_base", GrantableRolesAtBase);
            writer.WriteCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_grantable_roles_at_hq>("grantable_roles_at_hq", GrantableRolesAtHq);
            writer.WriteCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_grantable_roles_at_other>("grantable_roles_at_other", GrantableRolesAtOther);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_roles>("roles", Roles);
            writer.WriteCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_roles_at_base>("roles_at_base", RolesAtBase);
            writer.WriteCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_roles_at_hq>("roles_at_hq", RolesAtHq);
            writer.WriteCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdTitlesGet_roles_at_other>("roles_at_other", RolesAtOther);
            writer.WriteLongValue("title_id", TitleId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
