// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace EveStableInfrastructure.Models
{
    /// <summary>Assigned career path</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CorporationsProjectsDetailDetails_career
    {
        [EnumMember(Value = "Unspecified")]
        #pragma warning disable CS1591
        Unspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "Explorer")]
        #pragma warning disable CS1591
        Explorer,
        #pragma warning restore CS1591
        [EnumMember(Value = "Industrialist")]
        #pragma warning disable CS1591
        Industrialist,
        #pragma warning restore CS1591
        [EnumMember(Value = "Enforcer")]
        #pragma warning disable CS1591
        Enforcer,
        #pragma warning restore CS1591
        [EnumMember(Value = "Soldier of Fortune")]
        #pragma warning disable CS1591
        SoldierOfFortune,
        #pragma warning restore CS1591
    }
}
