// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CorporationsCorporationIdCustomsOfficesGet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Only present if alliance access is allowed</summary>
        public double? AllianceTaxRate { get; set; }
        /// <summary>standing_level and any standing related tax rate only present when this is true</summary>
        public bool? AllowAccessWithStandings { get; set; }
        /// <summary>The allow_alliance_access property</summary>
        public bool? AllowAllianceAccess { get; set; }
        /// <summary>The bad_standing_tax_rate property</summary>
        public double? BadStandingTaxRate { get; set; }
        /// <summary>The corporation_tax_rate property</summary>
        public double? CorporationTaxRate { get; set; }
        /// <summary>Tax rate for entities with excellent level of standing, only present if this level is allowed, same for all other standing related tax rates</summary>
        public double? ExcellentStandingTaxRate { get; set; }
        /// <summary>The good_standing_tax_rate property</summary>
        public double? GoodStandingTaxRate { get; set; }
        /// <summary>The neutral_standing_tax_rate property</summary>
        public double? NeutralStandingTaxRate { get; set; }
        /// <summary>unique ID of this customs office</summary>
        public long? OfficeId { get; set; }
        /// <summary>The reinforce_exit_end property</summary>
        public long? ReinforceExitEnd { get; set; }
        /// <summary>Together with reinforce_exit_end, marks a 2-hour period where this customs office could exit reinforcement mode during the day after initial attack</summary>
        public long? ReinforceExitStart { get; set; }
        /// <summary>Access is allowed only for entities with this level of standing or better</summary>
        public global::EveStableInfrastructure.Models.CorporationsCorporationIdCustomsOfficesGet_standing_level? StandingLevel { get; set; }
        /// <summary>ID of the solar system this customs office is located in</summary>
        public long? SystemId { get; set; }
        /// <summary>The terrible_standing_tax_rate property</summary>
        public double? TerribleStandingTaxRate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.CorporationsCorporationIdCustomsOfficesGet"/> and sets the default values.
        /// </summary>
        public CorporationsCorporationIdCustomsOfficesGet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsCorporationIdCustomsOfficesGet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.CorporationsCorporationIdCustomsOfficesGet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.CorporationsCorporationIdCustomsOfficesGet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alliance_tax_rate", n => { AllianceTaxRate = n.GetDoubleValue(); } },
                { "allow_access_with_standings", n => { AllowAccessWithStandings = n.GetBoolValue(); } },
                { "allow_alliance_access", n => { AllowAllianceAccess = n.GetBoolValue(); } },
                { "bad_standing_tax_rate", n => { BadStandingTaxRate = n.GetDoubleValue(); } },
                { "corporation_tax_rate", n => { CorporationTaxRate = n.GetDoubleValue(); } },
                { "excellent_standing_tax_rate", n => { ExcellentStandingTaxRate = n.GetDoubleValue(); } },
                { "good_standing_tax_rate", n => { GoodStandingTaxRate = n.GetDoubleValue(); } },
                { "neutral_standing_tax_rate", n => { NeutralStandingTaxRate = n.GetDoubleValue(); } },
                { "office_id", n => { OfficeId = n.GetLongValue(); } },
                { "reinforce_exit_end", n => { ReinforceExitEnd = n.GetLongValue(); } },
                { "reinforce_exit_start", n => { ReinforceExitStart = n.GetLongValue(); } },
                { "standing_level", n => { StandingLevel = n.GetEnumValue<global::EveStableInfrastructure.Models.CorporationsCorporationIdCustomsOfficesGet_standing_level>(); } },
                { "system_id", n => { SystemId = n.GetLongValue(); } },
                { "terrible_standing_tax_rate", n => { TerribleStandingTaxRate = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("alliance_tax_rate", AllianceTaxRate);
            writer.WriteBoolValue("allow_access_with_standings", AllowAccessWithStandings);
            writer.WriteBoolValue("allow_alliance_access", AllowAllianceAccess);
            writer.WriteDoubleValue("bad_standing_tax_rate", BadStandingTaxRate);
            writer.WriteDoubleValue("corporation_tax_rate", CorporationTaxRate);
            writer.WriteDoubleValue("excellent_standing_tax_rate", ExcellentStandingTaxRate);
            writer.WriteDoubleValue("good_standing_tax_rate", GoodStandingTaxRate);
            writer.WriteDoubleValue("neutral_standing_tax_rate", NeutralStandingTaxRate);
            writer.WriteLongValue("office_id", OfficeId);
            writer.WriteLongValue("reinforce_exit_end", ReinforceExitEnd);
            writer.WriteLongValue("reinforce_exit_start", ReinforceExitStart);
            writer.WriteEnumValue<global::EveStableInfrastructure.Models.CorporationsCorporationIdCustomsOfficesGet_standing_level>("standing_level", StandingLevel);
            writer.WriteLongValue("system_id", SystemId);
            writer.WriteDoubleValue("terrible_standing_tax_rate", TerribleStandingTaxRate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
