// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace EveStableInfrastructure.Models
{
    /// <summary>Participant&apos;s state</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CorporationsFreelanceJobsParticipantsParticipant_state
    {
        [EnumMember(Value = "Unspecified")]
        #pragma warning disable CS1591
        Unspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "Committed")]
        #pragma warning disable CS1591
        Committed,
        #pragma warning restore CS1591
        [EnumMember(Value = "Kicked")]
        #pragma warning disable CS1591
        Kicked,
        #pragma warning restore CS1591
        [EnumMember(Value = "Resigned")]
        #pragma warning disable CS1591
        Resigned,
        #pragma warning restore CS1591
    }
}
