// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    /// <summary>
    /// Remote repair armor
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CorporationsProjectsDetailConfigurationremoterepairarmor : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Identity of capsuleer to repair</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_identities>? Identities { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_identities> Identities { get; set; }
#endif
        /// <summary>Location of capsuleer&apos;s ship to repair</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_locations>? Locations { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_locations> Locations { get; set; }
#endif
        /// <summary>Ship-type of capsuleer&apos;s ship to repair</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_ships>? Ships { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_ships> Ships { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor"/> and sets the default values.
        /// </summary>
        public CorporationsProjectsDetailConfigurationremoterepairarmor()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "identities", n => { Identities = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_identities>(global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_identities.CreateFromDiscriminatorValue)?.AsList(); } },
                { "locations", n => { Locations = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_locations>(global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_locations.CreateFromDiscriminatorValue)?.AsList(); } },
                { "ships", n => { Ships = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_ships>(global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_ships.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_identities>("identities", Identities);
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_locations>("locations", Locations);
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_ships>("ships", Ships);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember1"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember2"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember3"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember4"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CorporationsProjectsDetailConfigurationremoterepairarmor_identities : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember1? CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember1 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember1 CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember2? CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember2 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember2 CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember3? CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember3 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember3 CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember4? CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember4 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember4 CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember4 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_identities"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_identities CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_identities();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember1 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember2 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember3 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember3();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember4 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember4();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember1 != null)
                {
                    return CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember1.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember2 != null)
                {
                    return CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember2.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember3 != null)
                {
                    return CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember3.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember4 != null)
                {
                    return CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember4.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember1 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember1>(null, CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember1);
                }
                else if(CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember2 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember2>(null, CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember2);
                }
                else if(CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember3 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember3>(null, CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember3);
                }
                else if(CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember4 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_identitiesMember4>(null, CorporationsProjectsDetailConfigurationremoterepairarmorIdentitiesMember4);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember1"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember2"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember3"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CorporationsProjectsDetailConfigurationremoterepairarmor_locations : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember1? CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember1 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember1 CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember2? CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember2 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember2 CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember3? CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember3 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember3 CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember3 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_locations"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_locations CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_locations();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember1 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember2 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember3 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember3();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember1 != null)
                {
                    return CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember1.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember2 != null)
                {
                    return CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember2.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember3 != null)
                {
                    return CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember3.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember1 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember1>(null, CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember1);
                }
                else if(CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember2 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember2>(null, CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember2);
                }
                else if(CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember3 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_locationsMember3>(null, CorporationsProjectsDetailConfigurationremoterepairarmorLocationsMember3);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_shipsMember1"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_shipsMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CorporationsProjectsDetailConfigurationremoterepairarmor_ships : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_shipsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_shipsMember1? CorporationsProjectsDetailConfigurationremoterepairarmorShipsMember1 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_shipsMember1 CorporationsProjectsDetailConfigurationremoterepairarmorShipsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_shipsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_shipsMember2? CorporationsProjectsDetailConfigurationremoterepairarmorShipsMember2 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_shipsMember2 CorporationsProjectsDetailConfigurationremoterepairarmorShipsMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_ships"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_ships CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor.CorporationsProjectsDetailConfigurationremoterepairarmor_ships();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationremoterepairarmorShipsMember1 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_shipsMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationremoterepairarmorShipsMember2 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_shipsMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CorporationsProjectsDetailConfigurationremoterepairarmorShipsMember1 != null)
                {
                    return CorporationsProjectsDetailConfigurationremoterepairarmorShipsMember1.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationremoterepairarmorShipsMember2 != null)
                {
                    return CorporationsProjectsDetailConfigurationremoterepairarmorShipsMember2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CorporationsProjectsDetailConfigurationremoterepairarmorShipsMember1 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_shipsMember1>(null, CorporationsProjectsDetailConfigurationremoterepairarmorShipsMember1);
                }
                else if(CorporationsProjectsDetailConfigurationremoterepairarmorShipsMember2 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationremoterepairarmor_shipsMember2>(null, CorporationsProjectsDetailConfigurationremoterepairarmorShipsMember2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
