// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CorporationsCorporationIdRolesHistoryGet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The changed_at property</summary>
        public DateTimeOffset? ChangedAt { get; set; }
        /// <summary>The character whose roles are changed</summary>
        public long? CharacterId { get; set; }
        /// <summary>ID of the character who issued this change</summary>
        public long? IssuerId { get; set; }
        /// <summary>The new_roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdRolesHistoryGet_new_roles?>? NewRoles { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdRolesHistoryGet_new_roles?> NewRoles { get; set; }
#endif
        /// <summary>The old_roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdRolesHistoryGet_old_roles?>? OldRoles { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsCorporationIdRolesHistoryGet_old_roles?> OldRoles { get; set; }
#endif
        /// <summary>The role_type property</summary>
        public global::EveStableInfrastructure.Models.CorporationsCorporationIdRolesHistoryGet_role_type? RoleType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.CorporationsCorporationIdRolesHistoryGet"/> and sets the default values.
        /// </summary>
        public CorporationsCorporationIdRolesHistoryGet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsCorporationIdRolesHistoryGet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.CorporationsCorporationIdRolesHistoryGet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.CorporationsCorporationIdRolesHistoryGet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "changed_at", n => { ChangedAt = n.GetDateTimeOffsetValue(); } },
                { "character_id", n => { CharacterId = n.GetLongValue(); } },
                { "issuer_id", n => { IssuerId = n.GetLongValue(); } },
                { "new_roles", n => { NewRoles = n.GetCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdRolesHistoryGet_new_roles>()?.AsList(); } },
                { "old_roles", n => { OldRoles = n.GetCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdRolesHistoryGet_old_roles>()?.AsList(); } },
                { "role_type", n => { RoleType = n.GetEnumValue<global::EveStableInfrastructure.Models.CorporationsCorporationIdRolesHistoryGet_role_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("changed_at", ChangedAt);
            writer.WriteLongValue("character_id", CharacterId);
            writer.WriteLongValue("issuer_id", IssuerId);
            writer.WriteCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdRolesHistoryGet_new_roles>("new_roles", NewRoles);
            writer.WriteCollectionOfEnumValues<global::EveStableInfrastructure.Models.CorporationsCorporationIdRolesHistoryGet_old_roles>("old_roles", OldRoles);
            writer.WriteEnumValue<global::EveStableInfrastructure.Models.CorporationsCorporationIdRolesHistoryGet_role_type>("role_type", RoleType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
