// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CorporationsCorporationIdShareholdersGet_shareholder_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "character")]
        #pragma warning disable CS1591
        Character,
        #pragma warning restore CS1591
        [EnumMember(Value = "corporation")]
        #pragma warning disable CS1591
        Corporation,
        #pragma warning restore CS1591
    }
}
