// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CorporationsCorporationIdMedalsIssuedGet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ID of the character who was rewarded this medal</summary>
        public long? CharacterId { get; set; }
        /// <summary>The issued_at property</summary>
        public DateTimeOffset? IssuedAt { get; set; }
        /// <summary>ID of the character who issued the medal</summary>
        public long? IssuerId { get; set; }
        /// <summary>The medal_id property</summary>
        public long? MedalId { get; set; }
        /// <summary>The reason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::EveStableInfrastructure.Models.CorporationsCorporationIdMedalsIssuedGet_status? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.CorporationsCorporationIdMedalsIssuedGet"/> and sets the default values.
        /// </summary>
        public CorporationsCorporationIdMedalsIssuedGet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsCorporationIdMedalsIssuedGet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.CorporationsCorporationIdMedalsIssuedGet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.CorporationsCorporationIdMedalsIssuedGet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "character_id", n => { CharacterId = n.GetLongValue(); } },
                { "issued_at", n => { IssuedAt = n.GetDateTimeOffsetValue(); } },
                { "issuer_id", n => { IssuerId = n.GetLongValue(); } },
                { "medal_id", n => { MedalId = n.GetLongValue(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::EveStableInfrastructure.Models.CorporationsCorporationIdMedalsIssuedGet_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("character_id", CharacterId);
            writer.WriteDateTimeOffsetValue("issued_at", IssuedAt);
            writer.WriteLongValue("issuer_id", IssuerId);
            writer.WriteLongValue("medal_id", MedalId);
            writer.WriteStringValue("reason", Reason);
            writer.WriteEnumValue<global::EveStableInfrastructure.Models.CorporationsCorporationIdMedalsIssuedGet_status>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
