// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    /// <summary>
    /// Scan signature
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CorporationsProjectsDetailConfigurationscansignature : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Locations of signatures</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature.CorporationsProjectsDetailConfigurationscansignature_locations>? Locations { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature.CorporationsProjectsDetailConfigurationscansignature_locations> Locations { get; set; }
#endif
        /// <summary>Signatures to scan</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationmatchersignature>? Signatures { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationmatchersignature> Signatures { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature"/> and sets the default values.
        /// </summary>
        public CorporationsProjectsDetailConfigurationscansignature()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "locations", n => { Locations = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature.CorporationsProjectsDetailConfigurationscansignature_locations>(global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature.CorporationsProjectsDetailConfigurationscansignature_locations.CreateFromDiscriminatorValue)?.AsList(); } },
                { "signatures", n => { Signatures = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationmatchersignature>(global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationmatchersignature.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature.CorporationsProjectsDetailConfigurationscansignature_locations>("locations", Locations);
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationmatchersignature>("signatures", Signatures);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember1"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember2"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember3"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CorporationsProjectsDetailConfigurationscansignature_locations : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember1? CorporationsProjectsDetailConfigurationscansignatureLocationsMember1 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember1 CorporationsProjectsDetailConfigurationscansignatureLocationsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember2? CorporationsProjectsDetailConfigurationscansignatureLocationsMember2 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember2 CorporationsProjectsDetailConfigurationscansignatureLocationsMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember3? CorporationsProjectsDetailConfigurationscansignatureLocationsMember3 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember3 CorporationsProjectsDetailConfigurationscansignatureLocationsMember3 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature.CorporationsProjectsDetailConfigurationscansignature_locations"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature.CorporationsProjectsDetailConfigurationscansignature_locations CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature.CorporationsProjectsDetailConfigurationscansignature_locations();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationscansignatureLocationsMember1 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationscansignatureLocationsMember2 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationscansignatureLocationsMember3 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember3();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CorporationsProjectsDetailConfigurationscansignatureLocationsMember1 != null)
                {
                    return CorporationsProjectsDetailConfigurationscansignatureLocationsMember1.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationscansignatureLocationsMember2 != null)
                {
                    return CorporationsProjectsDetailConfigurationscansignatureLocationsMember2.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationscansignatureLocationsMember3 != null)
                {
                    return CorporationsProjectsDetailConfigurationscansignatureLocationsMember3.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CorporationsProjectsDetailConfigurationscansignatureLocationsMember1 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember1>(null, CorporationsProjectsDetailConfigurationscansignatureLocationsMember1);
                }
                else if(CorporationsProjectsDetailConfigurationscansignatureLocationsMember2 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember2>(null, CorporationsProjectsDetailConfigurationscansignatureLocationsMember2);
                }
                else if(CorporationsProjectsDetailConfigurationscansignatureLocationsMember3 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationscansignature_locationsMember3>(null, CorporationsProjectsDetailConfigurationscansignatureLocationsMember3);
                }
            }
        }
    }
}
#pragma warning restore CS0618
