// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CorporationsCorporationIdFwStatsGet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The enlistment date of the given corporation into faction warfare. Will not be included if corporation is not enlisted in faction warfare</summary>
        public DateTimeOffset? EnlistedOn { get; set; }
        /// <summary>The faction the given corporation is enlisted to fight for. Will not be included if corporation is not enlisted in faction warfare</summary>
        public long? FactionId { get; set; }
        /// <summary>Summary of kills done by the given corporation against enemy factions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::EveStableInfrastructure.Models.CorporationsCorporationIdFwStatsGet_kills? Kills { get; set; }
#nullable restore
#else
        public global::EveStableInfrastructure.Models.CorporationsCorporationIdFwStatsGet_kills Kills { get; set; }
#endif
        /// <summary>How many pilots the enlisted corporation has. Will not be included if corporation is not enlisted in faction warfare</summary>
        public long? Pilots { get; set; }
        /// <summary>Summary of victory points gained by the given corporation for the enlisted faction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::EveStableInfrastructure.Models.CorporationsCorporationIdFwStatsGet_victory_points? VictoryPoints { get; set; }
#nullable restore
#else
        public global::EveStableInfrastructure.Models.CorporationsCorporationIdFwStatsGet_victory_points VictoryPoints { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.CorporationsCorporationIdFwStatsGet"/> and sets the default values.
        /// </summary>
        public CorporationsCorporationIdFwStatsGet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsCorporationIdFwStatsGet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.CorporationsCorporationIdFwStatsGet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.CorporationsCorporationIdFwStatsGet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enlisted_on", n => { EnlistedOn = n.GetDateTimeOffsetValue(); } },
                { "faction_id", n => { FactionId = n.GetLongValue(); } },
                { "kills", n => { Kills = n.GetObjectValue<global::EveStableInfrastructure.Models.CorporationsCorporationIdFwStatsGet_kills>(global::EveStableInfrastructure.Models.CorporationsCorporationIdFwStatsGet_kills.CreateFromDiscriminatorValue); } },
                { "pilots", n => { Pilots = n.GetLongValue(); } },
                { "victory_points", n => { VictoryPoints = n.GetObjectValue<global::EveStableInfrastructure.Models.CorporationsCorporationIdFwStatsGet_victory_points>(global::EveStableInfrastructure.Models.CorporationsCorporationIdFwStatsGet_victory_points.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("enlisted_on", EnlistedOn);
            writer.WriteLongValue("faction_id", FactionId);
            writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsCorporationIdFwStatsGet_kills>("kills", Kills);
            writer.WriteLongValue("pilots", Pilots);
            writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsCorporationIdFwStatsGet_victory_points>("victory_points", VictoryPoints);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
