// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace EveStableInfrastructure.Models
{
    /// <summary>Who can view the starbase (POS)&apos;s fule bay. Characters either need to have required role or belong to the starbase (POS) owner&apos;s corporation or alliance, as described by the enum, all other access settings follows the same scheme</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CorporationsCorporationIdStarbasesStarbaseIdGet_fuel_bay_view
    {
        [EnumMember(Value = "alliance_member")]
        #pragma warning disable CS1591
        Alliance_member,
        #pragma warning restore CS1591
        [EnumMember(Value = "config_starbase_equipment_role")]
        #pragma warning disable CS1591
        Config_starbase_equipment_role,
        #pragma warning restore CS1591
        [EnumMember(Value = "corporation_member")]
        #pragma warning disable CS1591
        Corporation_member,
        #pragma warning restore CS1591
        [EnumMember(Value = "starbase_fuel_technician_role")]
        #pragma warning disable CS1591
        Starbase_fuel_technician_role,
        #pragma warning restore CS1591
    }
}
