// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CorporationsCorporationIdWalletsDivisionJournalGet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount of ISK given or taken from the wallet as a result of the given transaction. Positive when ISK is deposited into the wallet and negative when ISK is withdrawn</summary>
        public double? Amount { get; set; }
        /// <summary>Wallet balance after transaction occurred</summary>
        public double? Balance { get; set; }
        /// <summary>An ID that gives extra context to the particular transaction. Because of legacy reasons the context is completely different per ref_type and means different things. It is also possible to not have a context_id</summary>
        public long? ContextId { get; set; }
        /// <summary>The type of the given context_id if present</summary>
        public global::EveStableInfrastructure.Models.CorporationsCorporationIdWalletsDivisionJournalGet_context_id_type? ContextIdType { get; set; }
        /// <summary>Date and time of transaction</summary>
        public DateTimeOffset? Date { get; set; }
        /// <summary>The reason for the transaction, mirrors what is seen in the client</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The id of the first party involved in the transaction. This attribute has no consistency and is different or non existant for particular ref_types. The description attribute will help make sense of what this attribute means. For more info about the given ID it can be dropped into the /universe/names/ ESI route to determine its type and name</summary>
        public long? FirstPartyId { get; set; }
        /// <summary>Unique journal reference ID</summary>
        public long? Id { get; set; }
        /// <summary>The user stated reason for the transaction. Only applies to some ref_types</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>&quot;The transaction type for the given. transaction. Different transaction types will populate different attributes. Note: If you have an existing XML API application that is using ref_types, you will need to know which string ESI ref_type maps to which integer. You can look at the following file to see string-&gt;int mappings: https://github.com/ccpgames/eve-glue/blob/master/eve_glue/wallet_journal_ref.py&quot;</summary>
        public global::EveStableInfrastructure.Models.CorporationsCorporationIdWalletsDivisionJournalGet_ref_type? RefType { get; set; }
        /// <summary>The id of the second party involved in the transaction. This attribute has no consistency and is different or non existant for particular ref_types. The description attribute will help make sense of what this attribute means. For more info about the given ID it can be dropped into the /universe/names/ ESI route to determine its type and name</summary>
        public long? SecondPartyId { get; set; }
        /// <summary>Tax amount received. Only applies to tax related transactions</summary>
        public double? Tax { get; set; }
        /// <summary>The corporation ID receiving any tax paid. Only applies to tax related transactions</summary>
        public long? TaxReceiverId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.CorporationsCorporationIdWalletsDivisionJournalGet"/> and sets the default values.
        /// </summary>
        public CorporationsCorporationIdWalletsDivisionJournalGet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsCorporationIdWalletsDivisionJournalGet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.CorporationsCorporationIdWalletsDivisionJournalGet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.CorporationsCorporationIdWalletsDivisionJournalGet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetDoubleValue(); } },
                { "balance", n => { Balance = n.GetDoubleValue(); } },
                { "context_id", n => { ContextId = n.GetLongValue(); } },
                { "context_id_type", n => { ContextIdType = n.GetEnumValue<global::EveStableInfrastructure.Models.CorporationsCorporationIdWalletsDivisionJournalGet_context_id_type>(); } },
                { "date", n => { Date = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "first_party_id", n => { FirstPartyId = n.GetLongValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "ref_type", n => { RefType = n.GetEnumValue<global::EveStableInfrastructure.Models.CorporationsCorporationIdWalletsDivisionJournalGet_ref_type>(); } },
                { "second_party_id", n => { SecondPartyId = n.GetLongValue(); } },
                { "tax", n => { Tax = n.GetDoubleValue(); } },
                { "tax_receiver_id", n => { TaxReceiverId = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("amount", Amount);
            writer.WriteDoubleValue("balance", Balance);
            writer.WriteLongValue("context_id", ContextId);
            writer.WriteEnumValue<global::EveStableInfrastructure.Models.CorporationsCorporationIdWalletsDivisionJournalGet_context_id_type>("context_id_type", ContextIdType);
            writer.WriteDateTimeOffsetValue("date", Date);
            writer.WriteStringValue("description", Description);
            writer.WriteLongValue("first_party_id", FirstPartyId);
            writer.WriteLongValue("id", Id);
            writer.WriteStringValue("reason", Reason);
            writer.WriteEnumValue<global::EveStableInfrastructure.Models.CorporationsCorporationIdWalletsDivisionJournalGet_ref_type>("ref_type", RefType);
            writer.WriteLongValue("second_party_id", SecondPartyId);
            writer.WriteDoubleValue("tax", Tax);
            writer.WriteLongValue("tax_receiver_id", TaxReceiverId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
