// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CorporationsCorporationIdStarbasesGet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The moon this starbase (POS) is anchored on, unanchored POSes do not have this information</summary>
        public long? MoonId { get; set; }
        /// <summary>When the POS onlined, for starbases (POSes) in online state</summary>
        public DateTimeOffset? OnlinedSince { get; set; }
        /// <summary>When the POS will be out of reinforcement, for starbases (POSes) in reinforced state</summary>
        public DateTimeOffset? ReinforcedUntil { get; set; }
        /// <summary>Unique ID for this starbase (POS)</summary>
        public long? StarbaseId { get; set; }
        /// <summary>The state property</summary>
        public global::EveStableInfrastructure.Models.CorporationsCorporationIdStarbasesGet_state? State { get; set; }
        /// <summary>The solar system this starbase (POS) is in, unanchored POSes have this information</summary>
        public long? SystemId { get; set; }
        /// <summary>Starbase (POS) type</summary>
        public long? TypeId { get; set; }
        /// <summary>When the POS started unanchoring, for starbases (POSes) in unanchoring state</summary>
        public DateTimeOffset? UnanchorAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.CorporationsCorporationIdStarbasesGet"/> and sets the default values.
        /// </summary>
        public CorporationsCorporationIdStarbasesGet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsCorporationIdStarbasesGet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.CorporationsCorporationIdStarbasesGet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.CorporationsCorporationIdStarbasesGet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "moon_id", n => { MoonId = n.GetLongValue(); } },
                { "onlined_since", n => { OnlinedSince = n.GetDateTimeOffsetValue(); } },
                { "reinforced_until", n => { ReinforcedUntil = n.GetDateTimeOffsetValue(); } },
                { "starbase_id", n => { StarbaseId = n.GetLongValue(); } },
                { "state", n => { State = n.GetEnumValue<global::EveStableInfrastructure.Models.CorporationsCorporationIdStarbasesGet_state>(); } },
                { "system_id", n => { SystemId = n.GetLongValue(); } },
                { "type_id", n => { TypeId = n.GetLongValue(); } },
                { "unanchor_at", n => { UnanchorAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("moon_id", MoonId);
            writer.WriteDateTimeOffsetValue("onlined_since", OnlinedSince);
            writer.WriteDateTimeOffsetValue("reinforced_until", ReinforcedUntil);
            writer.WriteLongValue("starbase_id", StarbaseId);
            writer.WriteEnumValue<global::EveStableInfrastructure.Models.CorporationsCorporationIdStarbasesGet_state>("state", State);
            writer.WriteLongValue("system_id", SystemId);
            writer.WriteLongValue("type_id", TypeId);
            writer.WriteDateTimeOffsetValue("unanchor_at", UnanchorAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
