// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace EveStableInfrastructure.Models
{
    /// <summary>Conflict type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CorporationsProjectsDetailConfigurationshipinsurance_conflict_type
    {
        [EnumMember(Value = "Any")]
        #pragma warning disable CS1591
        Any,
        #pragma warning restore CS1591
        [EnumMember(Value = "Pvp")]
        #pragma warning disable CS1591
        Pvp,
        #pragma warning restore CS1591
        [EnumMember(Value = "Pve")]
        #pragma warning disable CS1591
        Pve,
        #pragma warning restore CS1591
    }
}
