// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CorporationsCorporationIdRolesHistoryGet_role_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "grantable_roles")]
        #pragma warning disable CS1591
        Grantable_roles,
        #pragma warning restore CS1591
        [EnumMember(Value = "grantable_roles_at_base")]
        #pragma warning disable CS1591
        Grantable_roles_at_base,
        #pragma warning restore CS1591
        [EnumMember(Value = "grantable_roles_at_hq")]
        #pragma warning disable CS1591
        Grantable_roles_at_hq,
        #pragma warning restore CS1591
        [EnumMember(Value = "grantable_roles_at_other")]
        #pragma warning disable CS1591
        Grantable_roles_at_other,
        #pragma warning restore CS1591
        [EnumMember(Value = "roles")]
        #pragma warning disable CS1591
        Roles,
        #pragma warning restore CS1591
        [EnumMember(Value = "roles_at_base")]
        #pragma warning disable CS1591
        Roles_at_base,
        #pragma warning restore CS1591
        [EnumMember(Value = "roles_at_hq")]
        #pragma warning disable CS1591
        Roles_at_hq,
        #pragma warning restore CS1591
        [EnumMember(Value = "roles_at_other")]
        #pragma warning disable CS1591
        Roles_at_other,
        #pragma warning restore CS1591
    }
}
