// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    /// <summary>
    /// Damage ship
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CorporationsProjectsDetailConfigurationdamageship : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Identity of capsuleer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_identities>? Identities { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_identities> Identities { get; set; }
#endif
        /// <summary>Location of capsuleer&apos;s ship</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_locations>? Locations { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_locations> Locations { get; set; }
#endif
        /// <summary>Ship-type of capsuleer&apos;s ship</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_ships>? Ships { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_ships> Ships { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship"/> and sets the default values.
        /// </summary>
        public CorporationsProjectsDetailConfigurationdamageship()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "identities", n => { Identities = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_identities>(global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_identities.CreateFromDiscriminatorValue)?.AsList(); } },
                { "locations", n => { Locations = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_locations>(global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_locations.CreateFromDiscriminatorValue)?.AsList(); } },
                { "ships", n => { Ships = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_ships>(global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_ships.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_identities>("identities", Identities);
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_locations>("locations", Locations);
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_ships>("ships", Ships);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember1"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember2"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember3"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember4"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CorporationsProjectsDetailConfigurationdamageship_identities : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember1? CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember1 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember1 CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember2? CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember2 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember2 CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember3? CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember3 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember3 CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember4? CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember4 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember4 CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember4 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_identities"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_identities CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_identities();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember1 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember2 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember3 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember3();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember4 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember4();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember1 != null)
                {
                    return CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember1.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember2 != null)
                {
                    return CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember2.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember3 != null)
                {
                    return CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember3.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember4 != null)
                {
                    return CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember4.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember1 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember1>(null, CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember1);
                }
                else if(CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember2 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember2>(null, CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember2);
                }
                else if(CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember3 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember3>(null, CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember3);
                }
                else if(CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember4 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_identitiesMember4>(null, CorporationsProjectsDetailConfigurationdamageshipIdentitiesMember4);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember1"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember2"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember3"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CorporationsProjectsDetailConfigurationdamageship_locations : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember1? CorporationsProjectsDetailConfigurationdamageshipLocationsMember1 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember1 CorporationsProjectsDetailConfigurationdamageshipLocationsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember2? CorporationsProjectsDetailConfigurationdamageshipLocationsMember2 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember2 CorporationsProjectsDetailConfigurationdamageshipLocationsMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember3? CorporationsProjectsDetailConfigurationdamageshipLocationsMember3 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember3 CorporationsProjectsDetailConfigurationdamageshipLocationsMember3 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_locations"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_locations CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_locations();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationdamageshipLocationsMember1 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationdamageshipLocationsMember2 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationdamageshipLocationsMember3 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember3();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CorporationsProjectsDetailConfigurationdamageshipLocationsMember1 != null)
                {
                    return CorporationsProjectsDetailConfigurationdamageshipLocationsMember1.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationdamageshipLocationsMember2 != null)
                {
                    return CorporationsProjectsDetailConfigurationdamageshipLocationsMember2.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationdamageshipLocationsMember3 != null)
                {
                    return CorporationsProjectsDetailConfigurationdamageshipLocationsMember3.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CorporationsProjectsDetailConfigurationdamageshipLocationsMember1 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember1>(null, CorporationsProjectsDetailConfigurationdamageshipLocationsMember1);
                }
                else if(CorporationsProjectsDetailConfigurationdamageshipLocationsMember2 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember2>(null, CorporationsProjectsDetailConfigurationdamageshipLocationsMember2);
                }
                else if(CorporationsProjectsDetailConfigurationdamageshipLocationsMember3 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_locationsMember3>(null, CorporationsProjectsDetailConfigurationdamageshipLocationsMember3);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_shipsMember1"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_shipsMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CorporationsProjectsDetailConfigurationdamageship_ships : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_shipsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_shipsMember1? CorporationsProjectsDetailConfigurationdamageshipShipsMember1 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_shipsMember1 CorporationsProjectsDetailConfigurationdamageshipShipsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_shipsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_shipsMember2? CorporationsProjectsDetailConfigurationdamageshipShipsMember2 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_shipsMember2 CorporationsProjectsDetailConfigurationdamageshipShipsMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_ships"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_ships CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship.CorporationsProjectsDetailConfigurationdamageship_ships();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationdamageshipShipsMember1 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_shipsMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationdamageshipShipsMember2 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_shipsMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CorporationsProjectsDetailConfigurationdamageshipShipsMember1 != null)
                {
                    return CorporationsProjectsDetailConfigurationdamageshipShipsMember1.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationdamageshipShipsMember2 != null)
                {
                    return CorporationsProjectsDetailConfigurationdamageshipShipsMember2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CorporationsProjectsDetailConfigurationdamageshipShipsMember1 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_shipsMember1>(null, CorporationsProjectsDetailConfigurationdamageshipShipsMember1);
                }
                else if(CorporationsProjectsDetailConfigurationdamageshipShipsMember2 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdamageship_shipsMember2>(null, CorporationsProjectsDetailConfigurationdamageshipShipsMember2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
