// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    /// <summary>
    /// Destroy NPC
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CorporationsProjectsDetailConfigurationdestroynpc : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Location of non-capsuleer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc.CorporationsProjectsDetailConfigurationdestroynpc_locations>? Locations { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc.CorporationsProjectsDetailConfigurationdestroynpc_locations> Locations { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc"/> and sets the default values.
        /// </summary>
        public CorporationsProjectsDetailConfigurationdestroynpc()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "locations", n => { Locations = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc.CorporationsProjectsDetailConfigurationdestroynpc_locations>(global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc.CorporationsProjectsDetailConfigurationdestroynpc_locations.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc.CorporationsProjectsDetailConfigurationdestroynpc_locations>("locations", Locations);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember1"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember2"/>, <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember3"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CorporationsProjectsDetailConfigurationdestroynpc_locations : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember1? CorporationsProjectsDetailConfigurationdestroynpcLocationsMember1 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember1 CorporationsProjectsDetailConfigurationdestroynpcLocationsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember2? CorporationsProjectsDetailConfigurationdestroynpcLocationsMember2 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember2 CorporationsProjectsDetailConfigurationdestroynpcLocationsMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember3? CorporationsProjectsDetailConfigurationdestroynpcLocationsMember3 { get; set; }
#nullable restore
#else
            public global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember3 CorporationsProjectsDetailConfigurationdestroynpcLocationsMember3 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc.CorporationsProjectsDetailConfigurationdestroynpc_locations"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc.CorporationsProjectsDetailConfigurationdestroynpc_locations CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc.CorporationsProjectsDetailConfigurationdestroynpc_locations();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationdestroynpcLocationsMember1 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationdestroynpcLocationsMember2 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CorporationsProjectsDetailConfigurationdestroynpcLocationsMember3 = new global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember3();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CorporationsProjectsDetailConfigurationdestroynpcLocationsMember1 != null)
                {
                    return CorporationsProjectsDetailConfigurationdestroynpcLocationsMember1.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationdestroynpcLocationsMember2 != null)
                {
                    return CorporationsProjectsDetailConfigurationdestroynpcLocationsMember2.GetFieldDeserializers();
                }
                else if(CorporationsProjectsDetailConfigurationdestroynpcLocationsMember3 != null)
                {
                    return CorporationsProjectsDetailConfigurationdestroynpcLocationsMember3.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CorporationsProjectsDetailConfigurationdestroynpcLocationsMember1 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember1>(null, CorporationsProjectsDetailConfigurationdestroynpcLocationsMember1);
                }
                else if(CorporationsProjectsDetailConfigurationdestroynpcLocationsMember2 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember2>(null, CorporationsProjectsDetailConfigurationdestroynpcLocationsMember2);
                }
                else if(CorporationsProjectsDetailConfigurationdestroynpcLocationsMember3 != null)
                {
                    writer.WriteObjectValue<global::EveStableInfrastructure.Models.CorporationsProjectsDetailConfigurationdestroynpc_locationsMember3>(null, CorporationsProjectsDetailConfigurationdestroynpcLocationsMember3);
                }
            }
        }
    }
}
#pragma warning restore CS0618
