// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FreelanceJobsDetailFreelancejob : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Job&apos;s ID</summary>
        public Guid? Id { get; set; }
        /// <summary>Job&apos;s last modified</summary>
        public DateTimeOffset? LastModified { get; set; }
        /// <summary>Job&apos;s name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Job&apos;s progress</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::EveStableInfrastructure.Models.FreelanceJobsDetailProgress? Progress { get; set; }
#nullable restore
#else
        public global::EveStableInfrastructure.Models.FreelanceJobsDetailProgress Progress { get; set; }
#endif
        /// <summary>Job&apos;s reward</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::EveStableInfrastructure.Models.FreelanceJobsDetailReward? Reward { get; set; }
#nullable restore
#else
        public global::EveStableInfrastructure.Models.FreelanceJobsDetailReward Reward { get; set; }
#endif
        /// <summary>Job&apos;s state</summary>
        public global::EveStableInfrastructure.Models.FreelanceJobsDetailFreelancejob_state? State { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.FreelanceJobsDetailFreelancejob"/> and sets the default values.
        /// </summary>
        public FreelanceJobsDetailFreelancejob()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.FreelanceJobsDetailFreelancejob"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.FreelanceJobsDetailFreelancejob CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.FreelanceJobsDetailFreelancejob();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetGuidValue(); } },
                { "last_modified", n => { LastModified = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "progress", n => { Progress = n.GetObjectValue<global::EveStableInfrastructure.Models.FreelanceJobsDetailProgress>(global::EveStableInfrastructure.Models.FreelanceJobsDetailProgress.CreateFromDiscriminatorValue); } },
                { "reward", n => { Reward = n.GetObjectValue<global::EveStableInfrastructure.Models.FreelanceJobsDetailReward>(global::EveStableInfrastructure.Models.FreelanceJobsDetailReward.CreateFromDiscriminatorValue); } },
                { "state", n => { State = n.GetEnumValue<global::EveStableInfrastructure.Models.FreelanceJobsDetailFreelancejob_state>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("id", Id);
            writer.WriteDateTimeOffsetValue("last_modified", LastModified);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::EveStableInfrastructure.Models.FreelanceJobsDetailProgress>("progress", Progress);
            writer.WriteObjectValue<global::EveStableInfrastructure.Models.FreelanceJobsDetailReward>("reward", Reward);
            writer.WriteEnumValue<global::EveStableInfrastructure.Models.FreelanceJobsDetailFreelancejob_state>("state", State);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
