// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    /// <summary>
    /// Creator
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FreelanceJobsDetailCreator : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Character that created the job</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::EveStableInfrastructure.Models.FreelanceJobsDetailCreatorcharacter? Character { get; set; }
#nullable restore
#else
        public global::EveStableInfrastructure.Models.FreelanceJobsDetailCreatorcharacter Character { get; set; }
#endif
        /// <summary>Corporation that created the job</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::EveStableInfrastructure.Models.FreelanceJobsDetailCreatorcorporation? Corporation { get; set; }
#nullable restore
#else
        public global::EveStableInfrastructure.Models.FreelanceJobsDetailCreatorcorporation Corporation { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.FreelanceJobsDetailCreator"/> and sets the default values.
        /// </summary>
        public FreelanceJobsDetailCreator()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.FreelanceJobsDetailCreator"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.FreelanceJobsDetailCreator CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.FreelanceJobsDetailCreator();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "character", n => { Character = n.GetObjectValue<global::EveStableInfrastructure.Models.FreelanceJobsDetailCreatorcharacter>(global::EveStableInfrastructure.Models.FreelanceJobsDetailCreatorcharacter.CreateFromDiscriminatorValue); } },
                { "corporation", n => { Corporation = n.GetObjectValue<global::EveStableInfrastructure.Models.FreelanceJobsDetailCreatorcorporation>(global::EveStableInfrastructure.Models.FreelanceJobsDetailCreatorcorporation.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::EveStableInfrastructure.Models.FreelanceJobsDetailCreatorcharacter>("character", Character);
            writer.WriteObjectValue<global::EveStableInfrastructure.Models.FreelanceJobsDetailCreatorcorporation>("corporation", Corporation);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
