// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MarketsRegionIdHistoryGet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The average property</summary>
        public double? Average { get; set; }
        /// <summary>The date of this historical statistic entry</summary>
        public Date? Date { get; set; }
        /// <summary>The highest property</summary>
        public double? Highest { get; set; }
        /// <summary>The lowest property</summary>
        public double? Lowest { get; set; }
        /// <summary>Total number of orders happened that day</summary>
        public long? OrderCount { get; set; }
        /// <summary>Total</summary>
        public long? Volume { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.MarketsRegionIdHistoryGet"/> and sets the default values.
        /// </summary>
        public MarketsRegionIdHistoryGet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.MarketsRegionIdHistoryGet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.MarketsRegionIdHistoryGet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.MarketsRegionIdHistoryGet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "average", n => { Average = n.GetDoubleValue(); } },
                { "date", n => { Date = n.GetDateValue(); } },
                { "highest", n => { Highest = n.GetDoubleValue(); } },
                { "lowest", n => { Lowest = n.GetDoubleValue(); } },
                { "order_count", n => { OrderCount = n.GetLongValue(); } },
                { "volume", n => { Volume = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("average", Average);
            writer.WriteDateValue("date", Date);
            writer.WriteDoubleValue("highest", Highest);
            writer.WriteDoubleValue("lowest", Lowest);
            writer.WriteLongValue("order_count", OrderCount);
            writer.WriteLongValue("volume", Volume);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
