// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MarketsGroupsMarketGroupIdGet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The market_group_id property</summary>
        public long? MarketGroupId { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The parent_group_id property</summary>
        public long? ParentGroupId { get; set; }
        /// <summary>The types property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<long?>? Types { get; set; }
#nullable restore
#else
        public List<long?> Types { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.MarketsGroupsMarketGroupIdGet"/> and sets the default values.
        /// </summary>
        public MarketsGroupsMarketGroupIdGet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.MarketsGroupsMarketGroupIdGet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.MarketsGroupsMarketGroupIdGet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.MarketsGroupsMarketGroupIdGet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "market_group_id", n => { MarketGroupId = n.GetLongValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parent_group_id", n => { ParentGroupId = n.GetLongValue(); } },
                { "types", n => { Types = n.GetCollectionOfPrimitiveValues<long?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteLongValue("market_group_id", MarketGroupId);
            writer.WriteStringValue("name", Name);
            writer.WriteLongValue("parent_group_id", ParentGroupId);
            writer.WriteCollectionOfPrimitiveValues<long?>("types", Types);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
