// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MarketsPricesGet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The adjusted_price property</summary>
        public double? AdjustedPrice { get; set; }
        /// <summary>The average_price property</summary>
        public double? AveragePrice { get; set; }
        /// <summary>The type_id property</summary>
        public long? TypeId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.MarketsPricesGet"/> and sets the default values.
        /// </summary>
        public MarketsPricesGet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.MarketsPricesGet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.MarketsPricesGet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.MarketsPricesGet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adjusted_price", n => { AdjustedPrice = n.GetDoubleValue(); } },
                { "average_price", n => { AveragePrice = n.GetDoubleValue(); } },
                { "type_id", n => { TypeId = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("adjusted_price", AdjustedPrice);
            writer.WriteDoubleValue("average_price", AveragePrice);
            writer.WriteLongValue("type_id", TypeId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
