// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace EveStableInfrastructure.Models
{
    /// <summary>Route&apos;s health status</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MetaStatusRoutestatus_status
    {
        [EnumMember(Value = "Unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "OK")]
        #pragma warning disable CS1591
        OK,
        #pragma warning restore CS1591
        [EnumMember(Value = "Degraded")]
        #pragma warning disable CS1591
        Degraded,
        #pragma warning restore CS1591
        [EnumMember(Value = "Down")]
        #pragma warning disable CS1591
        Down,
        #pragma warning restore CS1591
        [EnumMember(Value = "Recovering")]
        #pragma warning disable CS1591
        Recovering,
        #pragma warning restore CS1591
    }
}
