// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SovereigntyCampaignsGet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Score for all attacking parties, only present in Defense Events.</summary>
        public double? AttackersScore { get; set; }
        /// <summary>Unique ID for this campaign.</summary>
        public long? CampaignId { get; set; }
        /// <summary>The constellation in which the campaign will take place.</summary>
        public long? ConstellationId { get; set; }
        /// <summary>Defending alliance, only present in Defense Events</summary>
        public long? DefenderId { get; set; }
        /// <summary>Score for the defending alliance, only present in Defense Events.</summary>
        public double? DefenderScore { get; set; }
        /// <summary>Type of event this campaign is for. tcu_defense, ihub_defense and station_defense are referred to as &quot;Defense Events&quot;, station_freeport as &quot;Freeport Events&quot;.</summary>
        public global::EveStableInfrastructure.Models.SovereigntyCampaignsGet_event_type? EventType { get; set; }
        /// <summary>Alliance participating and their respective scores, only present in Freeport Events.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.SovereigntyCampaignsGet_participants>? Participants { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.SovereigntyCampaignsGet_participants> Participants { get; set; }
#endif
        /// <summary>The solar system the structure is located in.</summary>
        public long? SolarSystemId { get; set; }
        /// <summary>Time the event is scheduled to start.</summary>
        public DateTimeOffset? StartTime { get; set; }
        /// <summary>The structure item ID that is related to this campaign.</summary>
        public long? StructureId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.SovereigntyCampaignsGet"/> and sets the default values.
        /// </summary>
        public SovereigntyCampaignsGet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.SovereigntyCampaignsGet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.SovereigntyCampaignsGet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.SovereigntyCampaignsGet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attackers_score", n => { AttackersScore = n.GetDoubleValue(); } },
                { "campaign_id", n => { CampaignId = n.GetLongValue(); } },
                { "constellation_id", n => { ConstellationId = n.GetLongValue(); } },
                { "defender_id", n => { DefenderId = n.GetLongValue(); } },
                { "defender_score", n => { DefenderScore = n.GetDoubleValue(); } },
                { "event_type", n => { EventType = n.GetEnumValue<global::EveStableInfrastructure.Models.SovereigntyCampaignsGet_event_type>(); } },
                { "participants", n => { Participants = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.SovereigntyCampaignsGet_participants>(global::EveStableInfrastructure.Models.SovereigntyCampaignsGet_participants.CreateFromDiscriminatorValue)?.AsList(); } },
                { "solar_system_id", n => { SolarSystemId = n.GetLongValue(); } },
                { "start_time", n => { StartTime = n.GetDateTimeOffsetValue(); } },
                { "structure_id", n => { StructureId = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("attackers_score", AttackersScore);
            writer.WriteLongValue("campaign_id", CampaignId);
            writer.WriteLongValue("constellation_id", ConstellationId);
            writer.WriteLongValue("defender_id", DefenderId);
            writer.WriteDoubleValue("defender_score", DefenderScore);
            writer.WriteEnumValue<global::EveStableInfrastructure.Models.SovereigntyCampaignsGet_event_type>("event_type", EventType);
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.SovereigntyCampaignsGet_participants>("participants", Participants);
            writer.WriteLongValue("solar_system_id", SolarSystemId);
            writer.WriteDateTimeOffsetValue("start_time", StartTime);
            writer.WriteLongValue("structure_id", StructureId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
