// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace EveStableInfrastructure.Models
{
    /// <summary>Type of event this campaign is for. tcu_defense, ihub_defense and station_defense are referred to as &quot;Defense Events&quot;, station_freeport as &quot;Freeport Events&quot;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SovereigntyCampaignsGet_event_type
    {
        [EnumMember(Value = "tcu_defense")]
        #pragma warning disable CS1591
        Tcu_defense,
        #pragma warning restore CS1591
        [EnumMember(Value = "ihub_defense")]
        #pragma warning disable CS1591
        Ihub_defense,
        #pragma warning restore CS1591
        [EnumMember(Value = "station_defense")]
        #pragma warning disable CS1591
        Station_defense,
        #pragma warning restore CS1591
        [EnumMember(Value = "station_freeport")]
        #pragma warning disable CS1591
        Station_freeport,
        #pragma warning restore CS1591
    }
}
