// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EveStableInfrastructure.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WarsWarIdGet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The aggressor corporation or alliance that declared this war, only contains either corporation_id or alliance_id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::EveStableInfrastructure.Models.WarsWarIdGet_aggressor? Aggressor { get; set; }
#nullable restore
#else
        public global::EveStableInfrastructure.Models.WarsWarIdGet_aggressor Aggressor { get; set; }
#endif
        /// <summary>allied corporations or alliances, each object contains either corporation_id or alliance_id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EveStableInfrastructure.Models.WarsWarIdGet_allies>? Allies { get; set; }
#nullable restore
#else
        public List<global::EveStableInfrastructure.Models.WarsWarIdGet_allies> Allies { get; set; }
#endif
        /// <summary>Time that the war was declared</summary>
        public DateTimeOffset? Declared { get; set; }
        /// <summary>The defending corporation or alliance that declared this war, only contains either corporation_id or alliance_id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::EveStableInfrastructure.Models.WarsWarIdGet_defender? Defender { get; set; }
#nullable restore
#else
        public global::EveStableInfrastructure.Models.WarsWarIdGet_defender Defender { get; set; }
#endif
        /// <summary>Time the war ended and shooting was no longer allowed</summary>
        public DateTimeOffset? Finished { get; set; }
        /// <summary>ID of the specified war</summary>
        public long? Id { get; set; }
        /// <summary>Was the war declared mutual by both parties</summary>
        public bool? Mutual { get; set; }
        /// <summary>Is the war currently open for allies or not</summary>
        public bool? OpenForAllies { get; set; }
        /// <summary>Time the war was retracted but both sides could still shoot each other</summary>
        public DateTimeOffset? Retracted { get; set; }
        /// <summary>Time when the war started and both sides could shoot each other</summary>
        public DateTimeOffset? Started { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Models.WarsWarIdGet"/> and sets the default values.
        /// </summary>
        public WarsWarIdGet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.WarsWarIdGet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EveStableInfrastructure.Models.WarsWarIdGet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EveStableInfrastructure.Models.WarsWarIdGet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aggressor", n => { Aggressor = n.GetObjectValue<global::EveStableInfrastructure.Models.WarsWarIdGet_aggressor>(global::EveStableInfrastructure.Models.WarsWarIdGet_aggressor.CreateFromDiscriminatorValue); } },
                { "allies", n => { Allies = n.GetCollectionOfObjectValues<global::EveStableInfrastructure.Models.WarsWarIdGet_allies>(global::EveStableInfrastructure.Models.WarsWarIdGet_allies.CreateFromDiscriminatorValue)?.AsList(); } },
                { "declared", n => { Declared = n.GetDateTimeOffsetValue(); } },
                { "defender", n => { Defender = n.GetObjectValue<global::EveStableInfrastructure.Models.WarsWarIdGet_defender>(global::EveStableInfrastructure.Models.WarsWarIdGet_defender.CreateFromDiscriminatorValue); } },
                { "finished", n => { Finished = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "mutual", n => { Mutual = n.GetBoolValue(); } },
                { "open_for_allies", n => { OpenForAllies = n.GetBoolValue(); } },
                { "retracted", n => { Retracted = n.GetDateTimeOffsetValue(); } },
                { "started", n => { Started = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::EveStableInfrastructure.Models.WarsWarIdGet_aggressor>("aggressor", Aggressor);
            writer.WriteCollectionOfObjectValues<global::EveStableInfrastructure.Models.WarsWarIdGet_allies>("allies", Allies);
            writer.WriteDateTimeOffsetValue("declared", Declared);
            writer.WriteObjectValue<global::EveStableInfrastructure.Models.WarsWarIdGet_defender>("defender", Defender);
            writer.WriteDateTimeOffsetValue("finished", Finished);
            writer.WriteLongValue("id", Id);
            writer.WriteBoolValue("mutual", Mutual);
            writer.WriteBoolValue("open_for_allies", OpenForAllies);
            writer.WriteDateTimeOffsetValue("retracted", Retracted);
            writer.WriteDateTimeOffsetValue("started", Started);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
