// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace EveStableInfrastructure.Characters.Item.Mail.Labels
{
    /// <summary>Hexadecimal string representing label color, in RGB format</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LabelsPostRequestBody_color
    {
        [EnumMember(Value = "#0000fe")]
        #pragma warning disable CS1591
        ZeroZeroZeroZerofe,
        #pragma warning restore CS1591
        [EnumMember(Value = "#006634")]
        #pragma warning disable CS1591
        ZeroZeroSixSixThreeFour,
        #pragma warning restore CS1591
        [EnumMember(Value = "#0099ff")]
        #pragma warning disable CS1591
        ZeroZeroNineNineff,
        #pragma warning restore CS1591
        [EnumMember(Value = "#00ff33")]
        #pragma warning disable CS1591
        ZeroZeroff33,
        #pragma warning restore CS1591
        [EnumMember(Value = "#01ffff")]
        #pragma warning disable CS1591
        ZeroOneffff,
        #pragma warning restore CS1591
        [EnumMember(Value = "#349800")]
        #pragma warning disable CS1591
        ThreeFourNineEightZeroZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "#660066")]
        #pragma warning disable CS1591
        SixSixZeroZeroSixSix,
        #pragma warning restore CS1591
        [EnumMember(Value = "#666666")]
        #pragma warning disable CS1591
        SixSixSixSixSixSix,
        #pragma warning restore CS1591
        [EnumMember(Value = "#999999")]
        #pragma warning disable CS1591
        NineNineNineNineNineNine,
        #pragma warning restore CS1591
        [EnumMember(Value = "#99ffff")]
        #pragma warning disable CS1591
        NineNineffff,
        #pragma warning restore CS1591
        [EnumMember(Value = "#9a0000")]
        #pragma warning disable CS1591
        Ninea0000,
        #pragma warning restore CS1591
        [EnumMember(Value = "#ccff9a")]
        #pragma warning disable CS1591
        Ccff9a,
        #pragma warning restore CS1591
        [EnumMember(Value = "#e6e6e6")]
        #pragma warning disable CS1591
        E6e6e6,
        #pragma warning restore CS1591
        [EnumMember(Value = "#fe0000")]
        #pragma warning disable CS1591
        Fe0000,
        #pragma warning restore CS1591
        [EnumMember(Value = "#ff6600")]
        #pragma warning disable CS1591
        Ff6600,
        #pragma warning restore CS1591
        [EnumMember(Value = "#ffff01")]
        #pragma warning disable CS1591
        Ffff01,
        #pragma warning restore CS1591
        [EnumMember(Value = "#ffffcd")]
        #pragma warning disable CS1591
        Ffffcd,
        #pragma warning restore CS1591
        [EnumMember(Value = "#ffffff")]
        #pragma warning disable CS1591
        Ffffff,
        #pragma warning restore CS1591
    }
}
