// <auto-generated/>
#pragma warning disable CS0618
using EveStableInfrastructure.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace EveStableInfrastructure.Corporations.Item.Starbases.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \corporations\{corporation_id}\starbases\{starbase_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithStarbase_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Corporations.Item.Starbases.Item.WithStarbase_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithStarbase_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/corporations/{corporation_id}/starbases/{starbase_id}?system_id={system_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Corporations.Item.Starbases.Item.WithStarbase_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithStarbase_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/corporations/{corporation_id}/starbases/{starbase_id}?system_id={system_id}", rawUrl)
        {
        }
        /// <summary>
        /// Returns various settings and fuels of a starbase (POS)
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsCorporationIdStarbasesStarbaseIdGet"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::EveStableInfrastructure.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::EveStableInfrastructure.Models.CorporationsCorporationIdStarbasesStarbaseIdGet?> GetAsync(Action<RequestConfiguration<global::EveStableInfrastructure.Corporations.Item.Starbases.Item.WithStarbase_ItemRequestBuilder.WithStarbase_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::EveStableInfrastructure.Models.CorporationsCorporationIdStarbasesStarbaseIdGet> GetAsync(Action<RequestConfiguration<global::EveStableInfrastructure.Corporations.Item.Starbases.Item.WithStarbase_ItemRequestBuilder.WithStarbase_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::EveStableInfrastructure.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::EveStableInfrastructure.Models.CorporationsCorporationIdStarbasesStarbaseIdGet>(requestInfo, global::EveStableInfrastructure.Models.CorporationsCorporationIdStarbasesStarbaseIdGet.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns various settings and fuels of a starbase (POS)
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::EveStableInfrastructure.Corporations.Item.Starbases.Item.WithStarbase_ItemRequestBuilder.WithStarbase_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::EveStableInfrastructure.Corporations.Item.Starbases.Item.WithStarbase_ItemRequestBuilder.WithStarbase_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Corporations.Item.Starbases.Item.WithStarbase_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::EveStableInfrastructure.Corporations.Item.Starbases.Item.WithStarbase_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::EveStableInfrastructure.Corporations.Item.Starbases.Item.WithStarbase_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns various settings and fuels of a starbase (POS)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithStarbase_ItemRequestBuilderGetQueryParameters 
        {
            [QueryParameter("system_id")]
            public long? SystemId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithStarbase_ItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::EveStableInfrastructure.Corporations.Item.Starbases.Item.WithStarbase_ItemRequestBuilder.WithStarbase_ItemRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
