// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace EveStableInfrastructure.Characters.Item.Search
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetCategoriesQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "agent")]
        #pragma warning disable CS1591
        Agent,
        #pragma warning restore CS1591
        [EnumMember(Value = "alliance")]
        #pragma warning disable CS1591
        Alliance,
        #pragma warning restore CS1591
        [EnumMember(Value = "character")]
        #pragma warning disable CS1591
        Character,
        #pragma warning restore CS1591
        [EnumMember(Value = "constellation")]
        #pragma warning disable CS1591
        Constellation,
        #pragma warning restore CS1591
        [EnumMember(Value = "corporation")]
        #pragma warning disable CS1591
        Corporation,
        #pragma warning restore CS1591
        [EnumMember(Value = "faction")]
        #pragma warning disable CS1591
        Faction,
        #pragma warning restore CS1591
        [EnumMember(Value = "inventory_type")]
        #pragma warning disable CS1591
        Inventory_type,
        #pragma warning restore CS1591
        [EnumMember(Value = "region")]
        #pragma warning disable CS1591
        Region,
        #pragma warning restore CS1591
        [EnumMember(Value = "solar_system")]
        #pragma warning disable CS1591
        Solar_system,
        #pragma warning restore CS1591
        [EnumMember(Value = "station")]
        #pragma warning disable CS1591
        Station,
        #pragma warning restore CS1591
        [EnumMember(Value = "structure")]
        #pragma warning disable CS1591
        Structure,
        #pragma warning restore CS1591
    }
}
