// <auto-generated/>
#pragma warning disable CS0618
using EveStableInfrastructure.Corporations.Item.Alliancehistory;
using EveStableInfrastructure.Corporations.Item.Assets;
using EveStableInfrastructure.Corporations.Item.Blueprints;
using EveStableInfrastructure.Corporations.Item.Contacts;
using EveStableInfrastructure.Corporations.Item.Containers;
using EveStableInfrastructure.Corporations.Item.Contracts;
using EveStableInfrastructure.Corporations.Item.Customs_offices;
using EveStableInfrastructure.Corporations.Item.Divisions;
using EveStableInfrastructure.Corporations.Item.Facilities;
using EveStableInfrastructure.Corporations.Item.FreelanceJobs;
using EveStableInfrastructure.Corporations.Item.Fw;
using EveStableInfrastructure.Corporations.Item.Icons;
using EveStableInfrastructure.Corporations.Item.Industry;
using EveStableInfrastructure.Corporations.Item.Killmails;
using EveStableInfrastructure.Corporations.Item.Medals;
using EveStableInfrastructure.Corporations.Item.Members;
using EveStableInfrastructure.Corporations.Item.Membertracking;
using EveStableInfrastructure.Corporations.Item.Orders;
using EveStableInfrastructure.Corporations.Item.Projects;
using EveStableInfrastructure.Corporations.Item.Roles;
using EveStableInfrastructure.Corporations.Item.Shareholders;
using EveStableInfrastructure.Corporations.Item.Standings;
using EveStableInfrastructure.Corporations.Item.Starbases;
using EveStableInfrastructure.Corporations.Item.Structures;
using EveStableInfrastructure.Corporations.Item.Titles;
using EveStableInfrastructure.Corporations.Item.Wallets;
using EveStableInfrastructure.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace EveStableInfrastructure.Corporations.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \corporations\{corporation_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithCorporation_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The alliancehistory property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Alliancehistory.AlliancehistoryRequestBuilder Alliancehistory
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Alliancehistory.AlliancehistoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assets property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Assets.AssetsRequestBuilder Assets
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Assets.AssetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The blueprints property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Blueprints.BlueprintsRequestBuilder Blueprints
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Blueprints.BlueprintsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contacts property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Contacts.ContactsRequestBuilder Contacts
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Contacts.ContactsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The containers property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Containers.ContainersRequestBuilder Containers
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Containers.ContainersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contracts property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Contracts.ContractsRequestBuilder Contracts
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Contracts.ContractsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The customs_offices property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Customs_offices.Customs_officesRequestBuilder Customs_offices
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Customs_offices.Customs_officesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The divisions property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Divisions.DivisionsRequestBuilder Divisions
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Divisions.DivisionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The facilities property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Facilities.FacilitiesRequestBuilder Facilities
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Facilities.FacilitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The freelanceJobs property</summary>
        public global::EveStableInfrastructure.Corporations.Item.FreelanceJobs.FreelanceJobsRequestBuilder FreelanceJobs
        {
            get => new global::EveStableInfrastructure.Corporations.Item.FreelanceJobs.FreelanceJobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fw property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Fw.FwRequestBuilder Fw
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Fw.FwRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The icons property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Icons.IconsRequestBuilder Icons
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Icons.IconsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The industry property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Industry.IndustryRequestBuilder Industry
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Industry.IndustryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The killmails property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Killmails.KillmailsRequestBuilder Killmails
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Killmails.KillmailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The medals property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Medals.MedalsRequestBuilder Medals
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Medals.MedalsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The members property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Members.MembersRequestBuilder Members
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Members.MembersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The membertracking property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Membertracking.MembertrackingRequestBuilder Membertracking
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Membertracking.MembertrackingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orders property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Orders.OrdersRequestBuilder Orders
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Orders.OrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projects property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Projects.ProjectsRequestBuilder Projects
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Projects.ProjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roles property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Roles.RolesRequestBuilder Roles
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shareholders property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Shareholders.ShareholdersRequestBuilder Shareholders
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Shareholders.ShareholdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The standings property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Standings.StandingsRequestBuilder Standings
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Standings.StandingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The starbases property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Starbases.StarbasesRequestBuilder Starbases
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Starbases.StarbasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The structures property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Structures.StructuresRequestBuilder Structures
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Structures.StructuresRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The titles property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Titles.TitlesRequestBuilder Titles
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Titles.TitlesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wallets property</summary>
        public global::EveStableInfrastructure.Corporations.Item.Wallets.WalletsRequestBuilder Wallets
        {
            get => new global::EveStableInfrastructure.Corporations.Item.Wallets.WalletsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Corporations.Item.WithCorporation_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCorporation_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/corporations/{corporation_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Corporations.Item.WithCorporation_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCorporation_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/corporations/{corporation_id}", rawUrl)
        {
        }
        /// <summary>
        /// Public information about a corporation
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CorporationsDetail"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::EveStableInfrastructure.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::EveStableInfrastructure.Models.CorporationsDetail?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::EveStableInfrastructure.Models.CorporationsDetail> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::EveStableInfrastructure.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::EveStableInfrastructure.Models.CorporationsDetail>(requestInfo, global::EveStableInfrastructure.Models.CorporationsDetail.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Public information about a corporation
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Corporations.Item.WithCorporation_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::EveStableInfrastructure.Corporations.Item.WithCorporation_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::EveStableInfrastructure.Corporations.Item.WithCorporation_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithCorporation_ItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
