// <auto-generated/>
#pragma warning disable CS0618
using EveStableInfrastructure.Ui.Openwindow.Contract;
using EveStableInfrastructure.Ui.Openwindow.Information;
using EveStableInfrastructure.Ui.Openwindow.Marketdetails;
using EveStableInfrastructure.Ui.Openwindow.Newmail;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EveStableInfrastructure.Ui.Openwindow
{
    /// <summary>
    /// Builds and executes requests for operations under \ui\openwindow
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OpenwindowRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The contract property</summary>
        public global::EveStableInfrastructure.Ui.Openwindow.Contract.ContractRequestBuilder Contract
        {
            get => new global::EveStableInfrastructure.Ui.Openwindow.Contract.ContractRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The information property</summary>
        public global::EveStableInfrastructure.Ui.Openwindow.Information.InformationRequestBuilder Information
        {
            get => new global::EveStableInfrastructure.Ui.Openwindow.Information.InformationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The marketdetails property</summary>
        public global::EveStableInfrastructure.Ui.Openwindow.Marketdetails.MarketdetailsRequestBuilder Marketdetails
        {
            get => new global::EveStableInfrastructure.Ui.Openwindow.Marketdetails.MarketdetailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The newmail property</summary>
        public global::EveStableInfrastructure.Ui.Openwindow.Newmail.NewmailRequestBuilder Newmail
        {
            get => new global::EveStableInfrastructure.Ui.Openwindow.Newmail.NewmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Ui.Openwindow.OpenwindowRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OpenwindowRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ui/openwindow", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Ui.Openwindow.OpenwindowRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OpenwindowRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ui/openwindow", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
