// <auto-generated/>
#pragma warning disable CS0618
using EveStableInfrastructure.Characters.Item.Agents_research;
using EveStableInfrastructure.Characters.Item.Assets;
using EveStableInfrastructure.Characters.Item.Attributes;
using EveStableInfrastructure.Characters.Item.Blueprints;
using EveStableInfrastructure.Characters.Item.Calendar;
using EveStableInfrastructure.Characters.Item.Clones;
using EveStableInfrastructure.Characters.Item.Contacts;
using EveStableInfrastructure.Characters.Item.Contracts;
using EveStableInfrastructure.Characters.Item.Corporationhistory;
using EveStableInfrastructure.Characters.Item.Cspa;
using EveStableInfrastructure.Characters.Item.Fatigue;
using EveStableInfrastructure.Characters.Item.Fittings;
using EveStableInfrastructure.Characters.Item.Fleet;
using EveStableInfrastructure.Characters.Item.FreelanceJobs;
using EveStableInfrastructure.Characters.Item.Fw;
using EveStableInfrastructure.Characters.Item.Implants;
using EveStableInfrastructure.Characters.Item.Industry;
using EveStableInfrastructure.Characters.Item.Killmails;
using EveStableInfrastructure.Characters.Item.Location;
using EveStableInfrastructure.Characters.Item.Loyalty;
using EveStableInfrastructure.Characters.Item.Mail;
using EveStableInfrastructure.Characters.Item.Medals;
using EveStableInfrastructure.Characters.Item.Mining;
using EveStableInfrastructure.Characters.Item.Notifications;
using EveStableInfrastructure.Characters.Item.Online;
using EveStableInfrastructure.Characters.Item.Orders;
using EveStableInfrastructure.Characters.Item.Planets;
using EveStableInfrastructure.Characters.Item.Portrait;
using EveStableInfrastructure.Characters.Item.Roles;
using EveStableInfrastructure.Characters.Item.Search;
using EveStableInfrastructure.Characters.Item.Ship;
using EveStableInfrastructure.Characters.Item.Skillqueue;
using EveStableInfrastructure.Characters.Item.Skills;
using EveStableInfrastructure.Characters.Item.Standings;
using EveStableInfrastructure.Characters.Item.Titles;
using EveStableInfrastructure.Characters.Item.Wallet;
using EveStableInfrastructure.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace EveStableInfrastructure.Characters.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \characters\{character_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithCharacter_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The agents_research property</summary>
        public global::EveStableInfrastructure.Characters.Item.Agents_research.Agents_researchRequestBuilder Agents_research
        {
            get => new global::EveStableInfrastructure.Characters.Item.Agents_research.Agents_researchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assets property</summary>
        public global::EveStableInfrastructure.Characters.Item.Assets.AssetsRequestBuilder Assets
        {
            get => new global::EveStableInfrastructure.Characters.Item.Assets.AssetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The attributes property</summary>
        public global::EveStableInfrastructure.Characters.Item.Attributes.AttributesRequestBuilder Attributes
        {
            get => new global::EveStableInfrastructure.Characters.Item.Attributes.AttributesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The blueprints property</summary>
        public global::EveStableInfrastructure.Characters.Item.Blueprints.BlueprintsRequestBuilder Blueprints
        {
            get => new global::EveStableInfrastructure.Characters.Item.Blueprints.BlueprintsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The calendar property</summary>
        public global::EveStableInfrastructure.Characters.Item.Calendar.CalendarRequestBuilder Calendar
        {
            get => new global::EveStableInfrastructure.Characters.Item.Calendar.CalendarRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The clones property</summary>
        public global::EveStableInfrastructure.Characters.Item.Clones.ClonesRequestBuilder Clones
        {
            get => new global::EveStableInfrastructure.Characters.Item.Clones.ClonesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contacts property</summary>
        public global::EveStableInfrastructure.Characters.Item.Contacts.ContactsRequestBuilder Contacts
        {
            get => new global::EveStableInfrastructure.Characters.Item.Contacts.ContactsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contracts property</summary>
        public global::EveStableInfrastructure.Characters.Item.Contracts.ContractsRequestBuilder Contracts
        {
            get => new global::EveStableInfrastructure.Characters.Item.Contracts.ContractsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The corporationhistory property</summary>
        public global::EveStableInfrastructure.Characters.Item.Corporationhistory.CorporationhistoryRequestBuilder Corporationhistory
        {
            get => new global::EveStableInfrastructure.Characters.Item.Corporationhistory.CorporationhistoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cspa property</summary>
        public global::EveStableInfrastructure.Characters.Item.Cspa.CspaRequestBuilder Cspa
        {
            get => new global::EveStableInfrastructure.Characters.Item.Cspa.CspaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fatigue property</summary>
        public global::EveStableInfrastructure.Characters.Item.Fatigue.FatigueRequestBuilder Fatigue
        {
            get => new global::EveStableInfrastructure.Characters.Item.Fatigue.FatigueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fittings property</summary>
        public global::EveStableInfrastructure.Characters.Item.Fittings.FittingsRequestBuilder Fittings
        {
            get => new global::EveStableInfrastructure.Characters.Item.Fittings.FittingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fleet property</summary>
        public global::EveStableInfrastructure.Characters.Item.Fleet.FleetRequestBuilder Fleet
        {
            get => new global::EveStableInfrastructure.Characters.Item.Fleet.FleetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The freelanceJobs property</summary>
        public global::EveStableInfrastructure.Characters.Item.FreelanceJobs.FreelanceJobsRequestBuilder FreelanceJobs
        {
            get => new global::EveStableInfrastructure.Characters.Item.FreelanceJobs.FreelanceJobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fw property</summary>
        public global::EveStableInfrastructure.Characters.Item.Fw.FwRequestBuilder Fw
        {
            get => new global::EveStableInfrastructure.Characters.Item.Fw.FwRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The implants property</summary>
        public global::EveStableInfrastructure.Characters.Item.Implants.ImplantsRequestBuilder Implants
        {
            get => new global::EveStableInfrastructure.Characters.Item.Implants.ImplantsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The industry property</summary>
        public global::EveStableInfrastructure.Characters.Item.Industry.IndustryRequestBuilder Industry
        {
            get => new global::EveStableInfrastructure.Characters.Item.Industry.IndustryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The killmails property</summary>
        public global::EveStableInfrastructure.Characters.Item.Killmails.KillmailsRequestBuilder Killmails
        {
            get => new global::EveStableInfrastructure.Characters.Item.Killmails.KillmailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The location property</summary>
        public global::EveStableInfrastructure.Characters.Item.Location.LocationRequestBuilder Location
        {
            get => new global::EveStableInfrastructure.Characters.Item.Location.LocationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The loyalty property</summary>
        public global::EveStableInfrastructure.Characters.Item.Loyalty.LoyaltyRequestBuilder Loyalty
        {
            get => new global::EveStableInfrastructure.Characters.Item.Loyalty.LoyaltyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mail property</summary>
        public global::EveStableInfrastructure.Characters.Item.Mail.MailRequestBuilder Mail
        {
            get => new global::EveStableInfrastructure.Characters.Item.Mail.MailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The medals property</summary>
        public global::EveStableInfrastructure.Characters.Item.Medals.MedalsRequestBuilder Medals
        {
            get => new global::EveStableInfrastructure.Characters.Item.Medals.MedalsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mining property</summary>
        public global::EveStableInfrastructure.Characters.Item.Mining.MiningRequestBuilder Mining
        {
            get => new global::EveStableInfrastructure.Characters.Item.Mining.MiningRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notifications property</summary>
        public global::EveStableInfrastructure.Characters.Item.Notifications.NotificationsRequestBuilder Notifications
        {
            get => new global::EveStableInfrastructure.Characters.Item.Notifications.NotificationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The online property</summary>
        public global::EveStableInfrastructure.Characters.Item.Online.OnlineRequestBuilder Online
        {
            get => new global::EveStableInfrastructure.Characters.Item.Online.OnlineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orders property</summary>
        public global::EveStableInfrastructure.Characters.Item.Orders.OrdersRequestBuilder Orders
        {
            get => new global::EveStableInfrastructure.Characters.Item.Orders.OrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The planets property</summary>
        public global::EveStableInfrastructure.Characters.Item.Planets.PlanetsRequestBuilder Planets
        {
            get => new global::EveStableInfrastructure.Characters.Item.Planets.PlanetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The portrait property</summary>
        public global::EveStableInfrastructure.Characters.Item.Portrait.PortraitRequestBuilder Portrait
        {
            get => new global::EveStableInfrastructure.Characters.Item.Portrait.PortraitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roles property</summary>
        public global::EveStableInfrastructure.Characters.Item.Roles.RolesRequestBuilder Roles
        {
            get => new global::EveStableInfrastructure.Characters.Item.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::EveStableInfrastructure.Characters.Item.Search.SearchRequestBuilder Search
        {
            get => new global::EveStableInfrastructure.Characters.Item.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ship property</summary>
        public global::EveStableInfrastructure.Characters.Item.Ship.ShipRequestBuilder Ship
        {
            get => new global::EveStableInfrastructure.Characters.Item.Ship.ShipRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The skillqueue property</summary>
        public global::EveStableInfrastructure.Characters.Item.Skillqueue.SkillqueueRequestBuilder Skillqueue
        {
            get => new global::EveStableInfrastructure.Characters.Item.Skillqueue.SkillqueueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The skills property</summary>
        public global::EveStableInfrastructure.Characters.Item.Skills.SkillsRequestBuilder Skills
        {
            get => new global::EveStableInfrastructure.Characters.Item.Skills.SkillsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The standings property</summary>
        public global::EveStableInfrastructure.Characters.Item.Standings.StandingsRequestBuilder Standings
        {
            get => new global::EveStableInfrastructure.Characters.Item.Standings.StandingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The titles property</summary>
        public global::EveStableInfrastructure.Characters.Item.Titles.TitlesRequestBuilder Titles
        {
            get => new global::EveStableInfrastructure.Characters.Item.Titles.TitlesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wallet property</summary>
        public global::EveStableInfrastructure.Characters.Item.Wallet.WalletRequestBuilder Wallet
        {
            get => new global::EveStableInfrastructure.Characters.Item.Wallet.WalletRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Characters.Item.WithCharacter_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCharacter_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/characters/{character_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EveStableInfrastructure.Characters.Item.WithCharacter_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCharacter_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/characters/{character_id}", rawUrl)
        {
        }
        /// <summary>
        /// Public information about a character
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Models.CharactersDetail"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::EveStableInfrastructure.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::EveStableInfrastructure.Models.CharactersDetail?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::EveStableInfrastructure.Models.CharactersDetail> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::EveStableInfrastructure.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::EveStableInfrastructure.Models.CharactersDetail>(requestInfo, global::EveStableInfrastructure.Models.CharactersDetail.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Public information about a character
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::EveStableInfrastructure.Characters.Item.WithCharacter_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::EveStableInfrastructure.Characters.Item.WithCharacter_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::EveStableInfrastructure.Characters.Item.WithCharacter_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithCharacter_ItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
